
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Absence` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Absence
 * 
 */
export type AbsenceModel = runtime.Types.Result.DefaultSelection<Prisma.$AbsencePayload>

export type AggregateAbsence = {
  _count: AbsenceCountAggregateOutputType | null
  _avg: AbsenceAvgAggregateOutputType | null
  _sum: AbsenceSumAggregateOutputType | null
  _min: AbsenceMinAggregateOutputType | null
  _max: AbsenceMaxAggregateOutputType | null
}

export type AbsenceAvgAggregateOutputType = {
  id: number | null
  studentId: number | null
  classId: number | null
  teacherId: number | null
  lateMinutes: number | null
}

export type AbsenceSumAggregateOutputType = {
  id: number | null
  studentId: number | null
  classId: number | null
  teacherId: number | null
  lateMinutes: number | null
}

export type AbsenceMinAggregateOutputType = {
  id: number | null
  studentId: number | null
  classId: number | null
  teacherId: number | null
  dateAbsence: Date | null
  hour: string | null
  hourEnd: string | null
  status: string | null
  lateMinutes: number | null
  validated: boolean | null
  validatedAt: Date | null
}

export type AbsenceMaxAggregateOutputType = {
  id: number | null
  studentId: number | null
  classId: number | null
  teacherId: number | null
  dateAbsence: Date | null
  hour: string | null
  hourEnd: string | null
  status: string | null
  lateMinutes: number | null
  validated: boolean | null
  validatedAt: Date | null
}

export type AbsenceCountAggregateOutputType = {
  id: number
  studentId: number
  classId: number
  teacherId: number
  dateAbsence: number
  hour: number
  hourEnd: number
  status: number
  lateMinutes: number
  validated: number
  validatedAt: number
  _all: number
}


export type AbsenceAvgAggregateInputType = {
  id?: true
  studentId?: true
  classId?: true
  teacherId?: true
  lateMinutes?: true
}

export type AbsenceSumAggregateInputType = {
  id?: true
  studentId?: true
  classId?: true
  teacherId?: true
  lateMinutes?: true
}

export type AbsenceMinAggregateInputType = {
  id?: true
  studentId?: true
  classId?: true
  teacherId?: true
  dateAbsence?: true
  hour?: true
  hourEnd?: true
  status?: true
  lateMinutes?: true
  validated?: true
  validatedAt?: true
}

export type AbsenceMaxAggregateInputType = {
  id?: true
  studentId?: true
  classId?: true
  teacherId?: true
  dateAbsence?: true
  hour?: true
  hourEnd?: true
  status?: true
  lateMinutes?: true
  validated?: true
  validatedAt?: true
}

export type AbsenceCountAggregateInputType = {
  id?: true
  studentId?: true
  classId?: true
  teacherId?: true
  dateAbsence?: true
  hour?: true
  hourEnd?: true
  status?: true
  lateMinutes?: true
  validated?: true
  validatedAt?: true
  _all?: true
}

export type AbsenceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Absence to aggregate.
   */
  where?: Prisma.AbsenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Absences to fetch.
   */
  orderBy?: Prisma.AbsenceOrderByWithRelationInput | Prisma.AbsenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AbsenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Absences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Absences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Absences
  **/
  _count?: true | AbsenceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AbsenceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AbsenceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AbsenceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AbsenceMaxAggregateInputType
}

export type GetAbsenceAggregateType<T extends AbsenceAggregateArgs> = {
      [P in keyof T & keyof AggregateAbsence]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAbsence[P]>
    : Prisma.GetScalarType<T[P], AggregateAbsence[P]>
}




export type AbsenceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AbsenceWhereInput
  orderBy?: Prisma.AbsenceOrderByWithAggregationInput | Prisma.AbsenceOrderByWithAggregationInput[]
  by: Prisma.AbsenceScalarFieldEnum[] | Prisma.AbsenceScalarFieldEnum
  having?: Prisma.AbsenceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AbsenceCountAggregateInputType | true
  _avg?: AbsenceAvgAggregateInputType
  _sum?: AbsenceSumAggregateInputType
  _min?: AbsenceMinAggregateInputType
  _max?: AbsenceMaxAggregateInputType
}

export type AbsenceGroupByOutputType = {
  id: number
  studentId: number | null
  classId: number | null
  teacherId: number | null
  dateAbsence: Date | null
  hour: string | null
  hourEnd: string | null
  status: string | null
  lateMinutes: number | null
  validated: boolean | null
  validatedAt: Date | null
  _count: AbsenceCountAggregateOutputType | null
  _avg: AbsenceAvgAggregateOutputType | null
  _sum: AbsenceSumAggregateOutputType | null
  _min: AbsenceMinAggregateOutputType | null
  _max: AbsenceMaxAggregateOutputType | null
}

type GetAbsenceGroupByPayload<T extends AbsenceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AbsenceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AbsenceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AbsenceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AbsenceGroupByOutputType[P]>
      }
    >
  >



export type AbsenceWhereInput = {
  AND?: Prisma.AbsenceWhereInput | Prisma.AbsenceWhereInput[]
  OR?: Prisma.AbsenceWhereInput[]
  NOT?: Prisma.AbsenceWhereInput | Prisma.AbsenceWhereInput[]
  id?: Prisma.IntFilter<"Absence"> | number
  studentId?: Prisma.IntNullableFilter<"Absence"> | number | null
  classId?: Prisma.IntNullableFilter<"Absence"> | number | null
  teacherId?: Prisma.IntNullableFilter<"Absence"> | number | null
  dateAbsence?: Prisma.DateTimeNullableFilter<"Absence"> | Date | string | null
  hour?: Prisma.StringNullableFilter<"Absence"> | string | null
  hourEnd?: Prisma.StringNullableFilter<"Absence"> | string | null
  status?: Prisma.StringNullableFilter<"Absence"> | string | null
  lateMinutes?: Prisma.IntNullableFilter<"Absence"> | number | null
  validated?: Prisma.BoolNullableFilter<"Absence"> | boolean | null
  validatedAt?: Prisma.DateTimeNullableFilter<"Absence"> | Date | string | null
  classe?: Prisma.XOR<Prisma.ClassNullableScalarRelationFilter, Prisma.ClassWhereInput> | null
  student?: Prisma.XOR<Prisma.StudentNullableScalarRelationFilter, Prisma.StudentWhereInput> | null
  teacher?: Prisma.XOR<Prisma.TeacherNullableScalarRelationFilter, Prisma.TeacherWhereInput> | null
}

export type AbsenceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrderInput | Prisma.SortOrder
  classId?: Prisma.SortOrderInput | Prisma.SortOrder
  teacherId?: Prisma.SortOrderInput | Prisma.SortOrder
  dateAbsence?: Prisma.SortOrderInput | Prisma.SortOrder
  hour?: Prisma.SortOrderInput | Prisma.SortOrder
  hourEnd?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  lateMinutes?: Prisma.SortOrderInput | Prisma.SortOrder
  validated?: Prisma.SortOrderInput | Prisma.SortOrder
  validatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  classe?: Prisma.ClassOrderByWithRelationInput
  student?: Prisma.StudentOrderByWithRelationInput
  teacher?: Prisma.TeacherOrderByWithRelationInput
}

export type AbsenceWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.AbsenceWhereInput | Prisma.AbsenceWhereInput[]
  OR?: Prisma.AbsenceWhereInput[]
  NOT?: Prisma.AbsenceWhereInput | Prisma.AbsenceWhereInput[]
  studentId?: Prisma.IntNullableFilter<"Absence"> | number | null
  classId?: Prisma.IntNullableFilter<"Absence"> | number | null
  teacherId?: Prisma.IntNullableFilter<"Absence"> | number | null
  dateAbsence?: Prisma.DateTimeNullableFilter<"Absence"> | Date | string | null
  hour?: Prisma.StringNullableFilter<"Absence"> | string | null
  hourEnd?: Prisma.StringNullableFilter<"Absence"> | string | null
  status?: Prisma.StringNullableFilter<"Absence"> | string | null
  lateMinutes?: Prisma.IntNullableFilter<"Absence"> | number | null
  validated?: Prisma.BoolNullableFilter<"Absence"> | boolean | null
  validatedAt?: Prisma.DateTimeNullableFilter<"Absence"> | Date | string | null
  classe?: Prisma.XOR<Prisma.ClassNullableScalarRelationFilter, Prisma.ClassWhereInput> | null
  student?: Prisma.XOR<Prisma.StudentNullableScalarRelationFilter, Prisma.StudentWhereInput> | null
  teacher?: Prisma.XOR<Prisma.TeacherNullableScalarRelationFilter, Prisma.TeacherWhereInput> | null
}, "id">

export type AbsenceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrderInput | Prisma.SortOrder
  classId?: Prisma.SortOrderInput | Prisma.SortOrder
  teacherId?: Prisma.SortOrderInput | Prisma.SortOrder
  dateAbsence?: Prisma.SortOrderInput | Prisma.SortOrder
  hour?: Prisma.SortOrderInput | Prisma.SortOrder
  hourEnd?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  lateMinutes?: Prisma.SortOrderInput | Prisma.SortOrder
  validated?: Prisma.SortOrderInput | Prisma.SortOrder
  validatedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AbsenceCountOrderByAggregateInput
  _avg?: Prisma.AbsenceAvgOrderByAggregateInput
  _max?: Prisma.AbsenceMaxOrderByAggregateInput
  _min?: Prisma.AbsenceMinOrderByAggregateInput
  _sum?: Prisma.AbsenceSumOrderByAggregateInput
}

export type AbsenceScalarWhereWithAggregatesInput = {
  AND?: Prisma.AbsenceScalarWhereWithAggregatesInput | Prisma.AbsenceScalarWhereWithAggregatesInput[]
  OR?: Prisma.AbsenceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AbsenceScalarWhereWithAggregatesInput | Prisma.AbsenceScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Absence"> | number
  studentId?: Prisma.IntNullableWithAggregatesFilter<"Absence"> | number | null
  classId?: Prisma.IntNullableWithAggregatesFilter<"Absence"> | number | null
  teacherId?: Prisma.IntNullableWithAggregatesFilter<"Absence"> | number | null
  dateAbsence?: Prisma.DateTimeNullableWithAggregatesFilter<"Absence"> | Date | string | null
  hour?: Prisma.StringNullableWithAggregatesFilter<"Absence"> | string | null
  hourEnd?: Prisma.StringNullableWithAggregatesFilter<"Absence"> | string | null
  status?: Prisma.StringNullableWithAggregatesFilter<"Absence"> | string | null
  lateMinutes?: Prisma.IntNullableWithAggregatesFilter<"Absence"> | number | null
  validated?: Prisma.BoolNullableWithAggregatesFilter<"Absence"> | boolean | null
  validatedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Absence"> | Date | string | null
}

export type AbsenceCreateInput = {
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
  classe?: Prisma.ClassCreateNestedOneWithoutAbsencesInput
  student?: Prisma.StudentCreateNestedOneWithoutAbsencesInput
  teacher?: Prisma.TeacherCreateNestedOneWithoutAbsencesInput
}

export type AbsenceUncheckedCreateInput = {
  id?: number
  studentId?: number | null
  classId?: number | null
  teacherId?: number | null
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
}

export type AbsenceUpdateInput = {
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  classe?: Prisma.ClassUpdateOneWithoutAbsencesNestedInput
  student?: Prisma.StudentUpdateOneWithoutAbsencesNestedInput
  teacher?: Prisma.TeacherUpdateOneWithoutAbsencesNestedInput
}

export type AbsenceUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AbsenceCreateManyInput = {
  id?: number
  studentId?: number | null
  classId?: number | null
  teacherId?: number | null
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
}

export type AbsenceUpdateManyMutationInput = {
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AbsenceUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AbsenceListRelationFilter = {
  every?: Prisma.AbsenceWhereInput
  some?: Prisma.AbsenceWhereInput
  none?: Prisma.AbsenceWhereInput
}

export type AbsenceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AbsenceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  dateAbsence?: Prisma.SortOrder
  hour?: Prisma.SortOrder
  hourEnd?: Prisma.SortOrder
  status?: Prisma.SortOrder
  lateMinutes?: Prisma.SortOrder
  validated?: Prisma.SortOrder
  validatedAt?: Prisma.SortOrder
}

export type AbsenceAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  lateMinutes?: Prisma.SortOrder
}

export type AbsenceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  dateAbsence?: Prisma.SortOrder
  hour?: Prisma.SortOrder
  hourEnd?: Prisma.SortOrder
  status?: Prisma.SortOrder
  lateMinutes?: Prisma.SortOrder
  validated?: Prisma.SortOrder
  validatedAt?: Prisma.SortOrder
}

export type AbsenceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  dateAbsence?: Prisma.SortOrder
  hour?: Prisma.SortOrder
  hourEnd?: Prisma.SortOrder
  status?: Prisma.SortOrder
  lateMinutes?: Prisma.SortOrder
  validated?: Prisma.SortOrder
  validatedAt?: Prisma.SortOrder
}

export type AbsenceSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  lateMinutes?: Prisma.SortOrder
}

export type AbsenceCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutStudentInput, Prisma.AbsenceUncheckedCreateWithoutStudentInput> | Prisma.AbsenceCreateWithoutStudentInput[] | Prisma.AbsenceUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutStudentInput | Prisma.AbsenceCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.AbsenceCreateManyStudentInputEnvelope
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
}

export type AbsenceUncheckedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutStudentInput, Prisma.AbsenceUncheckedCreateWithoutStudentInput> | Prisma.AbsenceCreateWithoutStudentInput[] | Prisma.AbsenceUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutStudentInput | Prisma.AbsenceCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.AbsenceCreateManyStudentInputEnvelope
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
}

export type AbsenceUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutStudentInput, Prisma.AbsenceUncheckedCreateWithoutStudentInput> | Prisma.AbsenceCreateWithoutStudentInput[] | Prisma.AbsenceUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutStudentInput | Prisma.AbsenceCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.AbsenceUpsertWithWhereUniqueWithoutStudentInput | Prisma.AbsenceUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.AbsenceCreateManyStudentInputEnvelope
  set?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  disconnect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  delete?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  update?: Prisma.AbsenceUpdateWithWhereUniqueWithoutStudentInput | Prisma.AbsenceUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.AbsenceUpdateManyWithWhereWithoutStudentInput | Prisma.AbsenceUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.AbsenceScalarWhereInput | Prisma.AbsenceScalarWhereInput[]
}

export type AbsenceUncheckedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutStudentInput, Prisma.AbsenceUncheckedCreateWithoutStudentInput> | Prisma.AbsenceCreateWithoutStudentInput[] | Prisma.AbsenceUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutStudentInput | Prisma.AbsenceCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.AbsenceUpsertWithWhereUniqueWithoutStudentInput | Prisma.AbsenceUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.AbsenceCreateManyStudentInputEnvelope
  set?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  disconnect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  delete?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  update?: Prisma.AbsenceUpdateWithWhereUniqueWithoutStudentInput | Prisma.AbsenceUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.AbsenceUpdateManyWithWhereWithoutStudentInput | Prisma.AbsenceUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.AbsenceScalarWhereInput | Prisma.AbsenceScalarWhereInput[]
}

export type AbsenceCreateNestedManyWithoutTeacherInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutTeacherInput, Prisma.AbsenceUncheckedCreateWithoutTeacherInput> | Prisma.AbsenceCreateWithoutTeacherInput[] | Prisma.AbsenceUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutTeacherInput | Prisma.AbsenceCreateOrConnectWithoutTeacherInput[]
  createMany?: Prisma.AbsenceCreateManyTeacherInputEnvelope
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
}

export type AbsenceUncheckedCreateNestedManyWithoutTeacherInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutTeacherInput, Prisma.AbsenceUncheckedCreateWithoutTeacherInput> | Prisma.AbsenceCreateWithoutTeacherInput[] | Prisma.AbsenceUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutTeacherInput | Prisma.AbsenceCreateOrConnectWithoutTeacherInput[]
  createMany?: Prisma.AbsenceCreateManyTeacherInputEnvelope
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
}

export type AbsenceUpdateManyWithoutTeacherNestedInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutTeacherInput, Prisma.AbsenceUncheckedCreateWithoutTeacherInput> | Prisma.AbsenceCreateWithoutTeacherInput[] | Prisma.AbsenceUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutTeacherInput | Prisma.AbsenceCreateOrConnectWithoutTeacherInput[]
  upsert?: Prisma.AbsenceUpsertWithWhereUniqueWithoutTeacherInput | Prisma.AbsenceUpsertWithWhereUniqueWithoutTeacherInput[]
  createMany?: Prisma.AbsenceCreateManyTeacherInputEnvelope
  set?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  disconnect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  delete?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  update?: Prisma.AbsenceUpdateWithWhereUniqueWithoutTeacherInput | Prisma.AbsenceUpdateWithWhereUniqueWithoutTeacherInput[]
  updateMany?: Prisma.AbsenceUpdateManyWithWhereWithoutTeacherInput | Prisma.AbsenceUpdateManyWithWhereWithoutTeacherInput[]
  deleteMany?: Prisma.AbsenceScalarWhereInput | Prisma.AbsenceScalarWhereInput[]
}

export type AbsenceUncheckedUpdateManyWithoutTeacherNestedInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutTeacherInput, Prisma.AbsenceUncheckedCreateWithoutTeacherInput> | Prisma.AbsenceCreateWithoutTeacherInput[] | Prisma.AbsenceUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutTeacherInput | Prisma.AbsenceCreateOrConnectWithoutTeacherInput[]
  upsert?: Prisma.AbsenceUpsertWithWhereUniqueWithoutTeacherInput | Prisma.AbsenceUpsertWithWhereUniqueWithoutTeacherInput[]
  createMany?: Prisma.AbsenceCreateManyTeacherInputEnvelope
  set?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  disconnect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  delete?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  update?: Prisma.AbsenceUpdateWithWhereUniqueWithoutTeacherInput | Prisma.AbsenceUpdateWithWhereUniqueWithoutTeacherInput[]
  updateMany?: Prisma.AbsenceUpdateManyWithWhereWithoutTeacherInput | Prisma.AbsenceUpdateManyWithWhereWithoutTeacherInput[]
  deleteMany?: Prisma.AbsenceScalarWhereInput | Prisma.AbsenceScalarWhereInput[]
}

export type AbsenceCreateNestedManyWithoutClasseInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutClasseInput, Prisma.AbsenceUncheckedCreateWithoutClasseInput> | Prisma.AbsenceCreateWithoutClasseInput[] | Prisma.AbsenceUncheckedCreateWithoutClasseInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutClasseInput | Prisma.AbsenceCreateOrConnectWithoutClasseInput[]
  createMany?: Prisma.AbsenceCreateManyClasseInputEnvelope
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
}

export type AbsenceUncheckedCreateNestedManyWithoutClasseInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutClasseInput, Prisma.AbsenceUncheckedCreateWithoutClasseInput> | Prisma.AbsenceCreateWithoutClasseInput[] | Prisma.AbsenceUncheckedCreateWithoutClasseInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutClasseInput | Prisma.AbsenceCreateOrConnectWithoutClasseInput[]
  createMany?: Prisma.AbsenceCreateManyClasseInputEnvelope
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
}

export type AbsenceUpdateManyWithoutClasseNestedInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutClasseInput, Prisma.AbsenceUncheckedCreateWithoutClasseInput> | Prisma.AbsenceCreateWithoutClasseInput[] | Prisma.AbsenceUncheckedCreateWithoutClasseInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutClasseInput | Prisma.AbsenceCreateOrConnectWithoutClasseInput[]
  upsert?: Prisma.AbsenceUpsertWithWhereUniqueWithoutClasseInput | Prisma.AbsenceUpsertWithWhereUniqueWithoutClasseInput[]
  createMany?: Prisma.AbsenceCreateManyClasseInputEnvelope
  set?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  disconnect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  delete?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  update?: Prisma.AbsenceUpdateWithWhereUniqueWithoutClasseInput | Prisma.AbsenceUpdateWithWhereUniqueWithoutClasseInput[]
  updateMany?: Prisma.AbsenceUpdateManyWithWhereWithoutClasseInput | Prisma.AbsenceUpdateManyWithWhereWithoutClasseInput[]
  deleteMany?: Prisma.AbsenceScalarWhereInput | Prisma.AbsenceScalarWhereInput[]
}

export type AbsenceUncheckedUpdateManyWithoutClasseNestedInput = {
  create?: Prisma.XOR<Prisma.AbsenceCreateWithoutClasseInput, Prisma.AbsenceUncheckedCreateWithoutClasseInput> | Prisma.AbsenceCreateWithoutClasseInput[] | Prisma.AbsenceUncheckedCreateWithoutClasseInput[]
  connectOrCreate?: Prisma.AbsenceCreateOrConnectWithoutClasseInput | Prisma.AbsenceCreateOrConnectWithoutClasseInput[]
  upsert?: Prisma.AbsenceUpsertWithWhereUniqueWithoutClasseInput | Prisma.AbsenceUpsertWithWhereUniqueWithoutClasseInput[]
  createMany?: Prisma.AbsenceCreateManyClasseInputEnvelope
  set?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  disconnect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  delete?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  connect?: Prisma.AbsenceWhereUniqueInput | Prisma.AbsenceWhereUniqueInput[]
  update?: Prisma.AbsenceUpdateWithWhereUniqueWithoutClasseInput | Prisma.AbsenceUpdateWithWhereUniqueWithoutClasseInput[]
  updateMany?: Prisma.AbsenceUpdateManyWithWhereWithoutClasseInput | Prisma.AbsenceUpdateManyWithWhereWithoutClasseInput[]
  deleteMany?: Prisma.AbsenceScalarWhereInput | Prisma.AbsenceScalarWhereInput[]
}

export type AbsenceCreateWithoutStudentInput = {
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
  classe?: Prisma.ClassCreateNestedOneWithoutAbsencesInput
  teacher?: Prisma.TeacherCreateNestedOneWithoutAbsencesInput
}

export type AbsenceUncheckedCreateWithoutStudentInput = {
  id?: number
  classId?: number | null
  teacherId?: number | null
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
}

export type AbsenceCreateOrConnectWithoutStudentInput = {
  where: Prisma.AbsenceWhereUniqueInput
  create: Prisma.XOR<Prisma.AbsenceCreateWithoutStudentInput, Prisma.AbsenceUncheckedCreateWithoutStudentInput>
}

export type AbsenceCreateManyStudentInputEnvelope = {
  data: Prisma.AbsenceCreateManyStudentInput | Prisma.AbsenceCreateManyStudentInput[]
  skipDuplicates?: boolean
}

export type AbsenceUpsertWithWhereUniqueWithoutStudentInput = {
  where: Prisma.AbsenceWhereUniqueInput
  update: Prisma.XOR<Prisma.AbsenceUpdateWithoutStudentInput, Prisma.AbsenceUncheckedUpdateWithoutStudentInput>
  create: Prisma.XOR<Prisma.AbsenceCreateWithoutStudentInput, Prisma.AbsenceUncheckedCreateWithoutStudentInput>
}

export type AbsenceUpdateWithWhereUniqueWithoutStudentInput = {
  where: Prisma.AbsenceWhereUniqueInput
  data: Prisma.XOR<Prisma.AbsenceUpdateWithoutStudentInput, Prisma.AbsenceUncheckedUpdateWithoutStudentInput>
}

export type AbsenceUpdateManyWithWhereWithoutStudentInput = {
  where: Prisma.AbsenceScalarWhereInput
  data: Prisma.XOR<Prisma.AbsenceUpdateManyMutationInput, Prisma.AbsenceUncheckedUpdateManyWithoutStudentInput>
}

export type AbsenceScalarWhereInput = {
  AND?: Prisma.AbsenceScalarWhereInput | Prisma.AbsenceScalarWhereInput[]
  OR?: Prisma.AbsenceScalarWhereInput[]
  NOT?: Prisma.AbsenceScalarWhereInput | Prisma.AbsenceScalarWhereInput[]
  id?: Prisma.IntFilter<"Absence"> | number
  studentId?: Prisma.IntNullableFilter<"Absence"> | number | null
  classId?: Prisma.IntNullableFilter<"Absence"> | number | null
  teacherId?: Prisma.IntNullableFilter<"Absence"> | number | null
  dateAbsence?: Prisma.DateTimeNullableFilter<"Absence"> | Date | string | null
  hour?: Prisma.StringNullableFilter<"Absence"> | string | null
  hourEnd?: Prisma.StringNullableFilter<"Absence"> | string | null
  status?: Prisma.StringNullableFilter<"Absence"> | string | null
  lateMinutes?: Prisma.IntNullableFilter<"Absence"> | number | null
  validated?: Prisma.BoolNullableFilter<"Absence"> | boolean | null
  validatedAt?: Prisma.DateTimeNullableFilter<"Absence"> | Date | string | null
}

export type AbsenceCreateWithoutTeacherInput = {
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
  classe?: Prisma.ClassCreateNestedOneWithoutAbsencesInput
  student?: Prisma.StudentCreateNestedOneWithoutAbsencesInput
}

export type AbsenceUncheckedCreateWithoutTeacherInput = {
  id?: number
  studentId?: number | null
  classId?: number | null
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
}

export type AbsenceCreateOrConnectWithoutTeacherInput = {
  where: Prisma.AbsenceWhereUniqueInput
  create: Prisma.XOR<Prisma.AbsenceCreateWithoutTeacherInput, Prisma.AbsenceUncheckedCreateWithoutTeacherInput>
}

export type AbsenceCreateManyTeacherInputEnvelope = {
  data: Prisma.AbsenceCreateManyTeacherInput | Prisma.AbsenceCreateManyTeacherInput[]
  skipDuplicates?: boolean
}

export type AbsenceUpsertWithWhereUniqueWithoutTeacherInput = {
  where: Prisma.AbsenceWhereUniqueInput
  update: Prisma.XOR<Prisma.AbsenceUpdateWithoutTeacherInput, Prisma.AbsenceUncheckedUpdateWithoutTeacherInput>
  create: Prisma.XOR<Prisma.AbsenceCreateWithoutTeacherInput, Prisma.AbsenceUncheckedCreateWithoutTeacherInput>
}

export type AbsenceUpdateWithWhereUniqueWithoutTeacherInput = {
  where: Prisma.AbsenceWhereUniqueInput
  data: Prisma.XOR<Prisma.AbsenceUpdateWithoutTeacherInput, Prisma.AbsenceUncheckedUpdateWithoutTeacherInput>
}

export type AbsenceUpdateManyWithWhereWithoutTeacherInput = {
  where: Prisma.AbsenceScalarWhereInput
  data: Prisma.XOR<Prisma.AbsenceUpdateManyMutationInput, Prisma.AbsenceUncheckedUpdateManyWithoutTeacherInput>
}

export type AbsenceCreateWithoutClasseInput = {
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
  student?: Prisma.StudentCreateNestedOneWithoutAbsencesInput
  teacher?: Prisma.TeacherCreateNestedOneWithoutAbsencesInput
}

export type AbsenceUncheckedCreateWithoutClasseInput = {
  id?: number
  studentId?: number | null
  teacherId?: number | null
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
}

export type AbsenceCreateOrConnectWithoutClasseInput = {
  where: Prisma.AbsenceWhereUniqueInput
  create: Prisma.XOR<Prisma.AbsenceCreateWithoutClasseInput, Prisma.AbsenceUncheckedCreateWithoutClasseInput>
}

export type AbsenceCreateManyClasseInputEnvelope = {
  data: Prisma.AbsenceCreateManyClasseInput | Prisma.AbsenceCreateManyClasseInput[]
  skipDuplicates?: boolean
}

export type AbsenceUpsertWithWhereUniqueWithoutClasseInput = {
  where: Prisma.AbsenceWhereUniqueInput
  update: Prisma.XOR<Prisma.AbsenceUpdateWithoutClasseInput, Prisma.AbsenceUncheckedUpdateWithoutClasseInput>
  create: Prisma.XOR<Prisma.AbsenceCreateWithoutClasseInput, Prisma.AbsenceUncheckedCreateWithoutClasseInput>
}

export type AbsenceUpdateWithWhereUniqueWithoutClasseInput = {
  where: Prisma.AbsenceWhereUniqueInput
  data: Prisma.XOR<Prisma.AbsenceUpdateWithoutClasseInput, Prisma.AbsenceUncheckedUpdateWithoutClasseInput>
}

export type AbsenceUpdateManyWithWhereWithoutClasseInput = {
  where: Prisma.AbsenceScalarWhereInput
  data: Prisma.XOR<Prisma.AbsenceUpdateManyMutationInput, Prisma.AbsenceUncheckedUpdateManyWithoutClasseInput>
}

export type AbsenceCreateManyStudentInput = {
  id?: number
  classId?: number | null
  teacherId?: number | null
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
}

export type AbsenceUpdateWithoutStudentInput = {
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  classe?: Prisma.ClassUpdateOneWithoutAbsencesNestedInput
  teacher?: Prisma.TeacherUpdateOneWithoutAbsencesNestedInput
}

export type AbsenceUncheckedUpdateWithoutStudentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AbsenceUncheckedUpdateManyWithoutStudentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AbsenceCreateManyTeacherInput = {
  id?: number
  studentId?: number | null
  classId?: number | null
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
}

export type AbsenceUpdateWithoutTeacherInput = {
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  classe?: Prisma.ClassUpdateOneWithoutAbsencesNestedInput
  student?: Prisma.StudentUpdateOneWithoutAbsencesNestedInput
}

export type AbsenceUncheckedUpdateWithoutTeacherInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AbsenceUncheckedUpdateManyWithoutTeacherInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AbsenceCreateManyClasseInput = {
  id?: number
  studentId?: number | null
  teacherId?: number | null
  dateAbsence?: Date | string | null
  hour?: string | null
  hourEnd?: string | null
  status?: string | null
  lateMinutes?: number | null
  validated?: boolean | null
  validatedAt?: Date | string | null
}

export type AbsenceUpdateWithoutClasseInput = {
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  student?: Prisma.StudentUpdateOneWithoutAbsencesNestedInput
  teacher?: Prisma.TeacherUpdateOneWithoutAbsencesNestedInput
}

export type AbsenceUncheckedUpdateWithoutClasseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AbsenceUncheckedUpdateManyWithoutClasseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateAbsence?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  hour?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hourEnd?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lateMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  validated?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  validatedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type AbsenceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentId?: boolean
  classId?: boolean
  teacherId?: boolean
  dateAbsence?: boolean
  hour?: boolean
  hourEnd?: boolean
  status?: boolean
  lateMinutes?: boolean
  validated?: boolean
  validatedAt?: boolean
  classe?: boolean | Prisma.Absence$classeArgs<ExtArgs>
  student?: boolean | Prisma.Absence$studentArgs<ExtArgs>
  teacher?: boolean | Prisma.Absence$teacherArgs<ExtArgs>
}, ExtArgs["result"]["absence"]>

export type AbsenceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentId?: boolean
  classId?: boolean
  teacherId?: boolean
  dateAbsence?: boolean
  hour?: boolean
  hourEnd?: boolean
  status?: boolean
  lateMinutes?: boolean
  validated?: boolean
  validatedAt?: boolean
  classe?: boolean | Prisma.Absence$classeArgs<ExtArgs>
  student?: boolean | Prisma.Absence$studentArgs<ExtArgs>
  teacher?: boolean | Prisma.Absence$teacherArgs<ExtArgs>
}, ExtArgs["result"]["absence"]>

export type AbsenceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentId?: boolean
  classId?: boolean
  teacherId?: boolean
  dateAbsence?: boolean
  hour?: boolean
  hourEnd?: boolean
  status?: boolean
  lateMinutes?: boolean
  validated?: boolean
  validatedAt?: boolean
  classe?: boolean | Prisma.Absence$classeArgs<ExtArgs>
  student?: boolean | Prisma.Absence$studentArgs<ExtArgs>
  teacher?: boolean | Prisma.Absence$teacherArgs<ExtArgs>
}, ExtArgs["result"]["absence"]>

export type AbsenceSelectScalar = {
  id?: boolean
  studentId?: boolean
  classId?: boolean
  teacherId?: boolean
  dateAbsence?: boolean
  hour?: boolean
  hourEnd?: boolean
  status?: boolean
  lateMinutes?: boolean
  validated?: boolean
  validatedAt?: boolean
}

export type AbsenceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "studentId" | "classId" | "teacherId" | "dateAbsence" | "hour" | "hourEnd" | "status" | "lateMinutes" | "validated" | "validatedAt", ExtArgs["result"]["absence"]>
export type AbsenceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  classe?: boolean | Prisma.Absence$classeArgs<ExtArgs>
  student?: boolean | Prisma.Absence$studentArgs<ExtArgs>
  teacher?: boolean | Prisma.Absence$teacherArgs<ExtArgs>
}
export type AbsenceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  classe?: boolean | Prisma.Absence$classeArgs<ExtArgs>
  student?: boolean | Prisma.Absence$studentArgs<ExtArgs>
  teacher?: boolean | Prisma.Absence$teacherArgs<ExtArgs>
}
export type AbsenceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  classe?: boolean | Prisma.Absence$classeArgs<ExtArgs>
  student?: boolean | Prisma.Absence$studentArgs<ExtArgs>
  teacher?: boolean | Prisma.Absence$teacherArgs<ExtArgs>
}

export type $AbsencePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Absence"
  objects: {
    classe: Prisma.$ClassPayload<ExtArgs> | null
    student: Prisma.$StudentPayload<ExtArgs> | null
    teacher: Prisma.$TeacherPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    studentId: number | null
    classId: number | null
    teacherId: number | null
    dateAbsence: Date | null
    hour: string | null
    hourEnd: string | null
    status: string | null
    lateMinutes: number | null
    validated: boolean | null
    validatedAt: Date | null
  }, ExtArgs["result"]["absence"]>
  composites: {}
}

export type AbsenceGetPayload<S extends boolean | null | undefined | AbsenceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AbsencePayload, S>

export type AbsenceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AbsenceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AbsenceCountAggregateInputType | true
  }

export interface AbsenceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Absence'], meta: { name: 'Absence' } }
  /**
   * Find zero or one Absence that matches the filter.
   * @param {AbsenceFindUniqueArgs} args - Arguments to find a Absence
   * @example
   * // Get one Absence
   * const absence = await prisma.absence.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AbsenceFindUniqueArgs>(args: Prisma.SelectSubset<T, AbsenceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AbsenceClient<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Absence that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AbsenceFindUniqueOrThrowArgs} args - Arguments to find a Absence
   * @example
   * // Get one Absence
   * const absence = await prisma.absence.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AbsenceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AbsenceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AbsenceClient<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Absence that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbsenceFindFirstArgs} args - Arguments to find a Absence
   * @example
   * // Get one Absence
   * const absence = await prisma.absence.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AbsenceFindFirstArgs>(args?: Prisma.SelectSubset<T, AbsenceFindFirstArgs<ExtArgs>>): Prisma.Prisma__AbsenceClient<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Absence that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbsenceFindFirstOrThrowArgs} args - Arguments to find a Absence
   * @example
   * // Get one Absence
   * const absence = await prisma.absence.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AbsenceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AbsenceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AbsenceClient<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Absences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbsenceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Absences
   * const absences = await prisma.absence.findMany()
   * 
   * // Get first 10 Absences
   * const absences = await prisma.absence.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const absenceWithIdOnly = await prisma.absence.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AbsenceFindManyArgs>(args?: Prisma.SelectSubset<T, AbsenceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Absence.
   * @param {AbsenceCreateArgs} args - Arguments to create a Absence.
   * @example
   * // Create one Absence
   * const Absence = await prisma.absence.create({
   *   data: {
   *     // ... data to create a Absence
   *   }
   * })
   * 
   */
  create<T extends AbsenceCreateArgs>(args: Prisma.SelectSubset<T, AbsenceCreateArgs<ExtArgs>>): Prisma.Prisma__AbsenceClient<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Absences.
   * @param {AbsenceCreateManyArgs} args - Arguments to create many Absences.
   * @example
   * // Create many Absences
   * const absence = await prisma.absence.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AbsenceCreateManyArgs>(args?: Prisma.SelectSubset<T, AbsenceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Absences and returns the data saved in the database.
   * @param {AbsenceCreateManyAndReturnArgs} args - Arguments to create many Absences.
   * @example
   * // Create many Absences
   * const absence = await prisma.absence.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Absences and only return the `id`
   * const absenceWithIdOnly = await prisma.absence.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AbsenceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AbsenceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Absence.
   * @param {AbsenceDeleteArgs} args - Arguments to delete one Absence.
   * @example
   * // Delete one Absence
   * const Absence = await prisma.absence.delete({
   *   where: {
   *     // ... filter to delete one Absence
   *   }
   * })
   * 
   */
  delete<T extends AbsenceDeleteArgs>(args: Prisma.SelectSubset<T, AbsenceDeleteArgs<ExtArgs>>): Prisma.Prisma__AbsenceClient<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Absence.
   * @param {AbsenceUpdateArgs} args - Arguments to update one Absence.
   * @example
   * // Update one Absence
   * const absence = await prisma.absence.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AbsenceUpdateArgs>(args: Prisma.SelectSubset<T, AbsenceUpdateArgs<ExtArgs>>): Prisma.Prisma__AbsenceClient<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Absences.
   * @param {AbsenceDeleteManyArgs} args - Arguments to filter Absences to delete.
   * @example
   * // Delete a few Absences
   * const { count } = await prisma.absence.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AbsenceDeleteManyArgs>(args?: Prisma.SelectSubset<T, AbsenceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Absences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbsenceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Absences
   * const absence = await prisma.absence.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AbsenceUpdateManyArgs>(args: Prisma.SelectSubset<T, AbsenceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Absences and returns the data updated in the database.
   * @param {AbsenceUpdateManyAndReturnArgs} args - Arguments to update many Absences.
   * @example
   * // Update many Absences
   * const absence = await prisma.absence.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Absences and only return the `id`
   * const absenceWithIdOnly = await prisma.absence.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AbsenceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AbsenceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Absence.
   * @param {AbsenceUpsertArgs} args - Arguments to update or create a Absence.
   * @example
   * // Update or create a Absence
   * const absence = await prisma.absence.upsert({
   *   create: {
   *     // ... data to create a Absence
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Absence we want to update
   *   }
   * })
   */
  upsert<T extends AbsenceUpsertArgs>(args: Prisma.SelectSubset<T, AbsenceUpsertArgs<ExtArgs>>): Prisma.Prisma__AbsenceClient<runtime.Types.Result.GetResult<Prisma.$AbsencePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Absences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbsenceCountArgs} args - Arguments to filter Absences to count.
   * @example
   * // Count the number of Absences
   * const count = await prisma.absence.count({
   *   where: {
   *     // ... the filter for the Absences we want to count
   *   }
   * })
  **/
  count<T extends AbsenceCountArgs>(
    args?: Prisma.Subset<T, AbsenceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AbsenceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Absence.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbsenceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AbsenceAggregateArgs>(args: Prisma.Subset<T, AbsenceAggregateArgs>): Prisma.PrismaPromise<GetAbsenceAggregateType<T>>

  /**
   * Group by Absence.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbsenceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AbsenceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AbsenceGroupByArgs['orderBy'] }
      : { orderBy?: AbsenceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AbsenceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAbsenceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Absence model
 */
readonly fields: AbsenceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Absence.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AbsenceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  classe<T extends Prisma.Absence$classeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Absence$classeArgs<ExtArgs>>): Prisma.Prisma__ClassClient<runtime.Types.Result.GetResult<Prisma.$ClassPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  student<T extends Prisma.Absence$studentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Absence$studentArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  teacher<T extends Prisma.Absence$teacherArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Absence$teacherArgs<ExtArgs>>): Prisma.Prisma__TeacherClient<runtime.Types.Result.GetResult<Prisma.$TeacherPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Absence model
 */
export interface AbsenceFieldRefs {
  readonly id: Prisma.FieldRef<"Absence", 'Int'>
  readonly studentId: Prisma.FieldRef<"Absence", 'Int'>
  readonly classId: Prisma.FieldRef<"Absence", 'Int'>
  readonly teacherId: Prisma.FieldRef<"Absence", 'Int'>
  readonly dateAbsence: Prisma.FieldRef<"Absence", 'DateTime'>
  readonly hour: Prisma.FieldRef<"Absence", 'String'>
  readonly hourEnd: Prisma.FieldRef<"Absence", 'String'>
  readonly status: Prisma.FieldRef<"Absence", 'String'>
  readonly lateMinutes: Prisma.FieldRef<"Absence", 'Int'>
  readonly validated: Prisma.FieldRef<"Absence", 'Boolean'>
  readonly validatedAt: Prisma.FieldRef<"Absence", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Absence findUnique
 */
export type AbsenceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceInclude<ExtArgs> | null
  /**
   * Filter, which Absence to fetch.
   */
  where: Prisma.AbsenceWhereUniqueInput
}

/**
 * Absence findUniqueOrThrow
 */
export type AbsenceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceInclude<ExtArgs> | null
  /**
   * Filter, which Absence to fetch.
   */
  where: Prisma.AbsenceWhereUniqueInput
}

/**
 * Absence findFirst
 */
export type AbsenceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceInclude<ExtArgs> | null
  /**
   * Filter, which Absence to fetch.
   */
  where?: Prisma.AbsenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Absences to fetch.
   */
  orderBy?: Prisma.AbsenceOrderByWithRelationInput | Prisma.AbsenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Absences.
   */
  cursor?: Prisma.AbsenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Absences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Absences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Absences.
   */
  distinct?: Prisma.AbsenceScalarFieldEnum | Prisma.AbsenceScalarFieldEnum[]
}

/**
 * Absence findFirstOrThrow
 */
export type AbsenceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceInclude<ExtArgs> | null
  /**
   * Filter, which Absence to fetch.
   */
  where?: Prisma.AbsenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Absences to fetch.
   */
  orderBy?: Prisma.AbsenceOrderByWithRelationInput | Prisma.AbsenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Absences.
   */
  cursor?: Prisma.AbsenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Absences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Absences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Absences.
   */
  distinct?: Prisma.AbsenceScalarFieldEnum | Prisma.AbsenceScalarFieldEnum[]
}

/**
 * Absence findMany
 */
export type AbsenceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceInclude<ExtArgs> | null
  /**
   * Filter, which Absences to fetch.
   */
  where?: Prisma.AbsenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Absences to fetch.
   */
  orderBy?: Prisma.AbsenceOrderByWithRelationInput | Prisma.AbsenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Absences.
   */
  cursor?: Prisma.AbsenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Absences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Absences.
   */
  skip?: number
  distinct?: Prisma.AbsenceScalarFieldEnum | Prisma.AbsenceScalarFieldEnum[]
}

/**
 * Absence create
 */
export type AbsenceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceInclude<ExtArgs> | null
  /**
   * The data needed to create a Absence.
   */
  data?: Prisma.XOR<Prisma.AbsenceCreateInput, Prisma.AbsenceUncheckedCreateInput>
}

/**
 * Absence createMany
 */
export type AbsenceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Absences.
   */
  data: Prisma.AbsenceCreateManyInput | Prisma.AbsenceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Absence createManyAndReturn
 */
export type AbsenceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * The data used to create many Absences.
   */
  data: Prisma.AbsenceCreateManyInput | Prisma.AbsenceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Absence update
 */
export type AbsenceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceInclude<ExtArgs> | null
  /**
   * The data needed to update a Absence.
   */
  data: Prisma.XOR<Prisma.AbsenceUpdateInput, Prisma.AbsenceUncheckedUpdateInput>
  /**
   * Choose, which Absence to update.
   */
  where: Prisma.AbsenceWhereUniqueInput
}

/**
 * Absence updateMany
 */
export type AbsenceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Absences.
   */
  data: Prisma.XOR<Prisma.AbsenceUpdateManyMutationInput, Prisma.AbsenceUncheckedUpdateManyInput>
  /**
   * Filter which Absences to update
   */
  where?: Prisma.AbsenceWhereInput
  /**
   * Limit how many Absences to update.
   */
  limit?: number
}

/**
 * Absence updateManyAndReturn
 */
export type AbsenceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * The data used to update Absences.
   */
  data: Prisma.XOR<Prisma.AbsenceUpdateManyMutationInput, Prisma.AbsenceUncheckedUpdateManyInput>
  /**
   * Filter which Absences to update
   */
  where?: Prisma.AbsenceWhereInput
  /**
   * Limit how many Absences to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Absence upsert
 */
export type AbsenceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceInclude<ExtArgs> | null
  /**
   * The filter to search for the Absence to update in case it exists.
   */
  where: Prisma.AbsenceWhereUniqueInput
  /**
   * In case the Absence found by the `where` argument doesn't exist, create a new Absence with this data.
   */
  create: Prisma.XOR<Prisma.AbsenceCreateInput, Prisma.AbsenceUncheckedCreateInput>
  /**
   * In case the Absence was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AbsenceUpdateInput, Prisma.AbsenceUncheckedUpdateInput>
}

/**
 * Absence delete
 */
export type AbsenceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceInclude<ExtArgs> | null
  /**
   * Filter which Absence to delete.
   */
  where: Prisma.AbsenceWhereUniqueInput
}

/**
 * Absence deleteMany
 */
export type AbsenceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Absences to delete
   */
  where?: Prisma.AbsenceWhereInput
  /**
   * Limit how many Absences to delete.
   */
  limit?: number
}

/**
 * Absence.classe
 */
export type Absence$classeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Class
   */
  select?: Prisma.ClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Class
   */
  omit?: Prisma.ClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClassInclude<ExtArgs> | null
  where?: Prisma.ClassWhereInput
}

/**
 * Absence.student
 */
export type Absence$studentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  where?: Prisma.StudentWhereInput
}

/**
 * Absence.teacher
 */
export type Absence$teacherArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Teacher
   */
  select?: Prisma.TeacherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Teacher
   */
  omit?: Prisma.TeacherOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeacherInclude<ExtArgs> | null
  where?: Prisma.TeacherWhereInput
}

/**
 * Absence without action
 */
export type AbsenceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Absence
   */
  select?: Prisma.AbsenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Absence
   */
  omit?: Prisma.AbsenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbsenceInclude<ExtArgs> | null
}
