
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PaymentLine` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PaymentLine
 * 
 */
export type PaymentLineModel = runtime.Types.Result.DefaultSelection<Prisma.$PaymentLinePayload>

export type AggregatePaymentLine = {
  _count: PaymentLineCountAggregateOutputType | null
  _avg: PaymentLineAvgAggregateOutputType | null
  _sum: PaymentLineSumAggregateOutputType | null
  _min: PaymentLineMinAggregateOutputType | null
  _max: PaymentLineMaxAggregateOutputType | null
}

export type PaymentLineAvgAggregateOutputType = {
  id: number | null
  paymentId: number | null
  amount: number | null
}

export type PaymentLineSumAggregateOutputType = {
  id: number | null
  paymentId: number | null
  amount: number | null
}

export type PaymentLineMinAggregateOutputType = {
  id: number | null
  paymentId: number | null
  amount: number | null
  title: string | null
  type: string | null
  numCheque: string | null
}

export type PaymentLineMaxAggregateOutputType = {
  id: number | null
  paymentId: number | null
  amount: number | null
  title: string | null
  type: string | null
  numCheque: string | null
}

export type PaymentLineCountAggregateOutputType = {
  id: number
  paymentId: number
  amount: number
  title: number
  type: number
  numCheque: number
  _all: number
}


export type PaymentLineAvgAggregateInputType = {
  id?: true
  paymentId?: true
  amount?: true
}

export type PaymentLineSumAggregateInputType = {
  id?: true
  paymentId?: true
  amount?: true
}

export type PaymentLineMinAggregateInputType = {
  id?: true
  paymentId?: true
  amount?: true
  title?: true
  type?: true
  numCheque?: true
}

export type PaymentLineMaxAggregateInputType = {
  id?: true
  paymentId?: true
  amount?: true
  title?: true
  type?: true
  numCheque?: true
}

export type PaymentLineCountAggregateInputType = {
  id?: true
  paymentId?: true
  amount?: true
  title?: true
  type?: true
  numCheque?: true
  _all?: true
}

export type PaymentLineAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PaymentLine to aggregate.
   */
  where?: Prisma.PaymentLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentLines to fetch.
   */
  orderBy?: Prisma.PaymentLineOrderByWithRelationInput | Prisma.PaymentLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PaymentLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PaymentLines
  **/
  _count?: true | PaymentLineCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PaymentLineAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PaymentLineSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PaymentLineMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PaymentLineMaxAggregateInputType
}

export type GetPaymentLineAggregateType<T extends PaymentLineAggregateArgs> = {
      [P in keyof T & keyof AggregatePaymentLine]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePaymentLine[P]>
    : Prisma.GetScalarType<T[P], AggregatePaymentLine[P]>
}




export type PaymentLineGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaymentLineWhereInput
  orderBy?: Prisma.PaymentLineOrderByWithAggregationInput | Prisma.PaymentLineOrderByWithAggregationInput[]
  by: Prisma.PaymentLineScalarFieldEnum[] | Prisma.PaymentLineScalarFieldEnum
  having?: Prisma.PaymentLineScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PaymentLineCountAggregateInputType | true
  _avg?: PaymentLineAvgAggregateInputType
  _sum?: PaymentLineSumAggregateInputType
  _min?: PaymentLineMinAggregateInputType
  _max?: PaymentLineMaxAggregateInputType
}

export type PaymentLineGroupByOutputType = {
  id: number
  paymentId: number
  amount: number
  title: string
  type: string
  numCheque: string | null
  _count: PaymentLineCountAggregateOutputType | null
  _avg: PaymentLineAvgAggregateOutputType | null
  _sum: PaymentLineSumAggregateOutputType | null
  _min: PaymentLineMinAggregateOutputType | null
  _max: PaymentLineMaxAggregateOutputType | null
}

type GetPaymentLineGroupByPayload<T extends PaymentLineGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PaymentLineGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PaymentLineGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PaymentLineGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PaymentLineGroupByOutputType[P]>
      }
    >
  >



export type PaymentLineWhereInput = {
  AND?: Prisma.PaymentLineWhereInput | Prisma.PaymentLineWhereInput[]
  OR?: Prisma.PaymentLineWhereInput[]
  NOT?: Prisma.PaymentLineWhereInput | Prisma.PaymentLineWhereInput[]
  id?: Prisma.IntFilter<"PaymentLine"> | number
  paymentId?: Prisma.IntFilter<"PaymentLine"> | number
  amount?: Prisma.FloatFilter<"PaymentLine"> | number
  title?: Prisma.StringFilter<"PaymentLine"> | string
  type?: Prisma.StringFilter<"PaymentLine"> | string
  numCheque?: Prisma.StringNullableFilter<"PaymentLine"> | string | null
  payment?: Prisma.XOR<Prisma.PaymentScalarRelationFilter, Prisma.PaymentWhereInput>
}

export type PaymentLineOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  numCheque?: Prisma.SortOrderInput | Prisma.SortOrder
  payment?: Prisma.PaymentOrderByWithRelationInput
}

export type PaymentLineWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.PaymentLineWhereInput | Prisma.PaymentLineWhereInput[]
  OR?: Prisma.PaymentLineWhereInput[]
  NOT?: Prisma.PaymentLineWhereInput | Prisma.PaymentLineWhereInput[]
  paymentId?: Prisma.IntFilter<"PaymentLine"> | number
  amount?: Prisma.FloatFilter<"PaymentLine"> | number
  title?: Prisma.StringFilter<"PaymentLine"> | string
  type?: Prisma.StringFilter<"PaymentLine"> | string
  numCheque?: Prisma.StringNullableFilter<"PaymentLine"> | string | null
  payment?: Prisma.XOR<Prisma.PaymentScalarRelationFilter, Prisma.PaymentWhereInput>
}, "id">

export type PaymentLineOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  numCheque?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PaymentLineCountOrderByAggregateInput
  _avg?: Prisma.PaymentLineAvgOrderByAggregateInput
  _max?: Prisma.PaymentLineMaxOrderByAggregateInput
  _min?: Prisma.PaymentLineMinOrderByAggregateInput
  _sum?: Prisma.PaymentLineSumOrderByAggregateInput
}

export type PaymentLineScalarWhereWithAggregatesInput = {
  AND?: Prisma.PaymentLineScalarWhereWithAggregatesInput | Prisma.PaymentLineScalarWhereWithAggregatesInput[]
  OR?: Prisma.PaymentLineScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PaymentLineScalarWhereWithAggregatesInput | Prisma.PaymentLineScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PaymentLine"> | number
  paymentId?: Prisma.IntWithAggregatesFilter<"PaymentLine"> | number
  amount?: Prisma.FloatWithAggregatesFilter<"PaymentLine"> | number
  title?: Prisma.StringWithAggregatesFilter<"PaymentLine"> | string
  type?: Prisma.StringWithAggregatesFilter<"PaymentLine"> | string
  numCheque?: Prisma.StringNullableWithAggregatesFilter<"PaymentLine"> | string | null
}

export type PaymentLineCreateInput = {
  amount: number
  title: string
  type: string
  numCheque?: string | null
  payment: Prisma.PaymentCreateNestedOneWithoutPaymentLinesInput
}

export type PaymentLineUncheckedCreateInput = {
  id?: number
  paymentId: number
  amount: number
  title: string
  type: string
  numCheque?: string | null
}

export type PaymentLineUpdateInput = {
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  numCheque?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payment?: Prisma.PaymentUpdateOneRequiredWithoutPaymentLinesNestedInput
}

export type PaymentLineUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  numCheque?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PaymentLineCreateManyInput = {
  id?: number
  paymentId: number
  amount: number
  title: string
  type: string
  numCheque?: string | null
}

export type PaymentLineUpdateManyMutationInput = {
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  numCheque?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PaymentLineUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  numCheque?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PaymentLineListRelationFilter = {
  every?: Prisma.PaymentLineWhereInput
  some?: Prisma.PaymentLineWhereInput
  none?: Prisma.PaymentLineWhereInput
}

export type PaymentLineOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PaymentLineCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  numCheque?: Prisma.SortOrder
}

export type PaymentLineAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type PaymentLineMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  numCheque?: Prisma.SortOrder
}

export type PaymentLineMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  numCheque?: Prisma.SortOrder
}

export type PaymentLineSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type PaymentLineCreateNestedManyWithoutPaymentInput = {
  create?: Prisma.XOR<Prisma.PaymentLineCreateWithoutPaymentInput, Prisma.PaymentLineUncheckedCreateWithoutPaymentInput> | Prisma.PaymentLineCreateWithoutPaymentInput[] | Prisma.PaymentLineUncheckedCreateWithoutPaymentInput[]
  connectOrCreate?: Prisma.PaymentLineCreateOrConnectWithoutPaymentInput | Prisma.PaymentLineCreateOrConnectWithoutPaymentInput[]
  createMany?: Prisma.PaymentLineCreateManyPaymentInputEnvelope
  connect?: Prisma.PaymentLineWhereUniqueInput | Prisma.PaymentLineWhereUniqueInput[]
}

export type PaymentLineUncheckedCreateNestedManyWithoutPaymentInput = {
  create?: Prisma.XOR<Prisma.PaymentLineCreateWithoutPaymentInput, Prisma.PaymentLineUncheckedCreateWithoutPaymentInput> | Prisma.PaymentLineCreateWithoutPaymentInput[] | Prisma.PaymentLineUncheckedCreateWithoutPaymentInput[]
  connectOrCreate?: Prisma.PaymentLineCreateOrConnectWithoutPaymentInput | Prisma.PaymentLineCreateOrConnectWithoutPaymentInput[]
  createMany?: Prisma.PaymentLineCreateManyPaymentInputEnvelope
  connect?: Prisma.PaymentLineWhereUniqueInput | Prisma.PaymentLineWhereUniqueInput[]
}

export type PaymentLineUpdateManyWithoutPaymentNestedInput = {
  create?: Prisma.XOR<Prisma.PaymentLineCreateWithoutPaymentInput, Prisma.PaymentLineUncheckedCreateWithoutPaymentInput> | Prisma.PaymentLineCreateWithoutPaymentInput[] | Prisma.PaymentLineUncheckedCreateWithoutPaymentInput[]
  connectOrCreate?: Prisma.PaymentLineCreateOrConnectWithoutPaymentInput | Prisma.PaymentLineCreateOrConnectWithoutPaymentInput[]
  upsert?: Prisma.PaymentLineUpsertWithWhereUniqueWithoutPaymentInput | Prisma.PaymentLineUpsertWithWhereUniqueWithoutPaymentInput[]
  createMany?: Prisma.PaymentLineCreateManyPaymentInputEnvelope
  set?: Prisma.PaymentLineWhereUniqueInput | Prisma.PaymentLineWhereUniqueInput[]
  disconnect?: Prisma.PaymentLineWhereUniqueInput | Prisma.PaymentLineWhereUniqueInput[]
  delete?: Prisma.PaymentLineWhereUniqueInput | Prisma.PaymentLineWhereUniqueInput[]
  connect?: Prisma.PaymentLineWhereUniqueInput | Prisma.PaymentLineWhereUniqueInput[]
  update?: Prisma.PaymentLineUpdateWithWhereUniqueWithoutPaymentInput | Prisma.PaymentLineUpdateWithWhereUniqueWithoutPaymentInput[]
  updateMany?: Prisma.PaymentLineUpdateManyWithWhereWithoutPaymentInput | Prisma.PaymentLineUpdateManyWithWhereWithoutPaymentInput[]
  deleteMany?: Prisma.PaymentLineScalarWhereInput | Prisma.PaymentLineScalarWhereInput[]
}

export type PaymentLineUncheckedUpdateManyWithoutPaymentNestedInput = {
  create?: Prisma.XOR<Prisma.PaymentLineCreateWithoutPaymentInput, Prisma.PaymentLineUncheckedCreateWithoutPaymentInput> | Prisma.PaymentLineCreateWithoutPaymentInput[] | Prisma.PaymentLineUncheckedCreateWithoutPaymentInput[]
  connectOrCreate?: Prisma.PaymentLineCreateOrConnectWithoutPaymentInput | Prisma.PaymentLineCreateOrConnectWithoutPaymentInput[]
  upsert?: Prisma.PaymentLineUpsertWithWhereUniqueWithoutPaymentInput | Prisma.PaymentLineUpsertWithWhereUniqueWithoutPaymentInput[]
  createMany?: Prisma.PaymentLineCreateManyPaymentInputEnvelope
  set?: Prisma.PaymentLineWhereUniqueInput | Prisma.PaymentLineWhereUniqueInput[]
  disconnect?: Prisma.PaymentLineWhereUniqueInput | Prisma.PaymentLineWhereUniqueInput[]
  delete?: Prisma.PaymentLineWhereUniqueInput | Prisma.PaymentLineWhereUniqueInput[]
  connect?: Prisma.PaymentLineWhereUniqueInput | Prisma.PaymentLineWhereUniqueInput[]
  update?: Prisma.PaymentLineUpdateWithWhereUniqueWithoutPaymentInput | Prisma.PaymentLineUpdateWithWhereUniqueWithoutPaymentInput[]
  updateMany?: Prisma.PaymentLineUpdateManyWithWhereWithoutPaymentInput | Prisma.PaymentLineUpdateManyWithWhereWithoutPaymentInput[]
  deleteMany?: Prisma.PaymentLineScalarWhereInput | Prisma.PaymentLineScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PaymentLineCreateWithoutPaymentInput = {
  amount: number
  title: string
  type: string
  numCheque?: string | null
}

export type PaymentLineUncheckedCreateWithoutPaymentInput = {
  id?: number
  amount: number
  title: string
  type: string
  numCheque?: string | null
}

export type PaymentLineCreateOrConnectWithoutPaymentInput = {
  where: Prisma.PaymentLineWhereUniqueInput
  create: Prisma.XOR<Prisma.PaymentLineCreateWithoutPaymentInput, Prisma.PaymentLineUncheckedCreateWithoutPaymentInput>
}

export type PaymentLineCreateManyPaymentInputEnvelope = {
  data: Prisma.PaymentLineCreateManyPaymentInput | Prisma.PaymentLineCreateManyPaymentInput[]
  skipDuplicates?: boolean
}

export type PaymentLineUpsertWithWhereUniqueWithoutPaymentInput = {
  where: Prisma.PaymentLineWhereUniqueInput
  update: Prisma.XOR<Prisma.PaymentLineUpdateWithoutPaymentInput, Prisma.PaymentLineUncheckedUpdateWithoutPaymentInput>
  create: Prisma.XOR<Prisma.PaymentLineCreateWithoutPaymentInput, Prisma.PaymentLineUncheckedCreateWithoutPaymentInput>
}

export type PaymentLineUpdateWithWhereUniqueWithoutPaymentInput = {
  where: Prisma.PaymentLineWhereUniqueInput
  data: Prisma.XOR<Prisma.PaymentLineUpdateWithoutPaymentInput, Prisma.PaymentLineUncheckedUpdateWithoutPaymentInput>
}

export type PaymentLineUpdateManyWithWhereWithoutPaymentInput = {
  where: Prisma.PaymentLineScalarWhereInput
  data: Prisma.XOR<Prisma.PaymentLineUpdateManyMutationInput, Prisma.PaymentLineUncheckedUpdateManyWithoutPaymentInput>
}

export type PaymentLineScalarWhereInput = {
  AND?: Prisma.PaymentLineScalarWhereInput | Prisma.PaymentLineScalarWhereInput[]
  OR?: Prisma.PaymentLineScalarWhereInput[]
  NOT?: Prisma.PaymentLineScalarWhereInput | Prisma.PaymentLineScalarWhereInput[]
  id?: Prisma.IntFilter<"PaymentLine"> | number
  paymentId?: Prisma.IntFilter<"PaymentLine"> | number
  amount?: Prisma.FloatFilter<"PaymentLine"> | number
  title?: Prisma.StringFilter<"PaymentLine"> | string
  type?: Prisma.StringFilter<"PaymentLine"> | string
  numCheque?: Prisma.StringNullableFilter<"PaymentLine"> | string | null
}

export type PaymentLineCreateManyPaymentInput = {
  id?: number
  amount: number
  title: string
  type: string
  numCheque?: string | null
}

export type PaymentLineUpdateWithoutPaymentInput = {
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  numCheque?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PaymentLineUncheckedUpdateWithoutPaymentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  numCheque?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PaymentLineUncheckedUpdateManyWithoutPaymentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  numCheque?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type PaymentLineSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  paymentId?: boolean
  amount?: boolean
  title?: boolean
  type?: boolean
  numCheque?: boolean
  payment?: boolean | Prisma.PaymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paymentLine"]>

export type PaymentLineSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  paymentId?: boolean
  amount?: boolean
  title?: boolean
  type?: boolean
  numCheque?: boolean
  payment?: boolean | Prisma.PaymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paymentLine"]>

export type PaymentLineSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  paymentId?: boolean
  amount?: boolean
  title?: boolean
  type?: boolean
  numCheque?: boolean
  payment?: boolean | Prisma.PaymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paymentLine"]>

export type PaymentLineSelectScalar = {
  id?: boolean
  paymentId?: boolean
  amount?: boolean
  title?: boolean
  type?: boolean
  numCheque?: boolean
}

export type PaymentLineOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "paymentId" | "amount" | "title" | "type" | "numCheque", ExtArgs["result"]["paymentLine"]>
export type PaymentLineInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  payment?: boolean | Prisma.PaymentDefaultArgs<ExtArgs>
}
export type PaymentLineIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  payment?: boolean | Prisma.PaymentDefaultArgs<ExtArgs>
}
export type PaymentLineIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  payment?: boolean | Prisma.PaymentDefaultArgs<ExtArgs>
}

export type $PaymentLinePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PaymentLine"
  objects: {
    payment: Prisma.$PaymentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    paymentId: number
    amount: number
    title: string
    type: string
    numCheque: string | null
  }, ExtArgs["result"]["paymentLine"]>
  composites: {}
}

export type PaymentLineGetPayload<S extends boolean | null | undefined | PaymentLineDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload, S>

export type PaymentLineCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PaymentLineFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PaymentLineCountAggregateInputType | true
  }

export interface PaymentLineDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PaymentLine'], meta: { name: 'PaymentLine' } }
  /**
   * Find zero or one PaymentLine that matches the filter.
   * @param {PaymentLineFindUniqueArgs} args - Arguments to find a PaymentLine
   * @example
   * // Get one PaymentLine
   * const paymentLine = await prisma.paymentLine.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PaymentLineFindUniqueArgs>(args: Prisma.SelectSubset<T, PaymentLineFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PaymentLineClient<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PaymentLine that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PaymentLineFindUniqueOrThrowArgs} args - Arguments to find a PaymentLine
   * @example
   * // Get one PaymentLine
   * const paymentLine = await prisma.paymentLine.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PaymentLineFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PaymentLineFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaymentLineClient<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PaymentLine that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLineFindFirstArgs} args - Arguments to find a PaymentLine
   * @example
   * // Get one PaymentLine
   * const paymentLine = await prisma.paymentLine.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PaymentLineFindFirstArgs>(args?: Prisma.SelectSubset<T, PaymentLineFindFirstArgs<ExtArgs>>): Prisma.Prisma__PaymentLineClient<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PaymentLine that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLineFindFirstOrThrowArgs} args - Arguments to find a PaymentLine
   * @example
   * // Get one PaymentLine
   * const paymentLine = await prisma.paymentLine.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PaymentLineFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PaymentLineFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaymentLineClient<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PaymentLines that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLineFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PaymentLines
   * const paymentLines = await prisma.paymentLine.findMany()
   * 
   * // Get first 10 PaymentLines
   * const paymentLines = await prisma.paymentLine.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const paymentLineWithIdOnly = await prisma.paymentLine.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PaymentLineFindManyArgs>(args?: Prisma.SelectSubset<T, PaymentLineFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PaymentLine.
   * @param {PaymentLineCreateArgs} args - Arguments to create a PaymentLine.
   * @example
   * // Create one PaymentLine
   * const PaymentLine = await prisma.paymentLine.create({
   *   data: {
   *     // ... data to create a PaymentLine
   *   }
   * })
   * 
   */
  create<T extends PaymentLineCreateArgs>(args: Prisma.SelectSubset<T, PaymentLineCreateArgs<ExtArgs>>): Prisma.Prisma__PaymentLineClient<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PaymentLines.
   * @param {PaymentLineCreateManyArgs} args - Arguments to create many PaymentLines.
   * @example
   * // Create many PaymentLines
   * const paymentLine = await prisma.paymentLine.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PaymentLineCreateManyArgs>(args?: Prisma.SelectSubset<T, PaymentLineCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PaymentLines and returns the data saved in the database.
   * @param {PaymentLineCreateManyAndReturnArgs} args - Arguments to create many PaymentLines.
   * @example
   * // Create many PaymentLines
   * const paymentLine = await prisma.paymentLine.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PaymentLines and only return the `id`
   * const paymentLineWithIdOnly = await prisma.paymentLine.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PaymentLineCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PaymentLineCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PaymentLine.
   * @param {PaymentLineDeleteArgs} args - Arguments to delete one PaymentLine.
   * @example
   * // Delete one PaymentLine
   * const PaymentLine = await prisma.paymentLine.delete({
   *   where: {
   *     // ... filter to delete one PaymentLine
   *   }
   * })
   * 
   */
  delete<T extends PaymentLineDeleteArgs>(args: Prisma.SelectSubset<T, PaymentLineDeleteArgs<ExtArgs>>): Prisma.Prisma__PaymentLineClient<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PaymentLine.
   * @param {PaymentLineUpdateArgs} args - Arguments to update one PaymentLine.
   * @example
   * // Update one PaymentLine
   * const paymentLine = await prisma.paymentLine.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PaymentLineUpdateArgs>(args: Prisma.SelectSubset<T, PaymentLineUpdateArgs<ExtArgs>>): Prisma.Prisma__PaymentLineClient<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PaymentLines.
   * @param {PaymentLineDeleteManyArgs} args - Arguments to filter PaymentLines to delete.
   * @example
   * // Delete a few PaymentLines
   * const { count } = await prisma.paymentLine.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PaymentLineDeleteManyArgs>(args?: Prisma.SelectSubset<T, PaymentLineDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PaymentLines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLineUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PaymentLines
   * const paymentLine = await prisma.paymentLine.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PaymentLineUpdateManyArgs>(args: Prisma.SelectSubset<T, PaymentLineUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PaymentLines and returns the data updated in the database.
   * @param {PaymentLineUpdateManyAndReturnArgs} args - Arguments to update many PaymentLines.
   * @example
   * // Update many PaymentLines
   * const paymentLine = await prisma.paymentLine.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PaymentLines and only return the `id`
   * const paymentLineWithIdOnly = await prisma.paymentLine.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PaymentLineUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PaymentLineUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PaymentLine.
   * @param {PaymentLineUpsertArgs} args - Arguments to update or create a PaymentLine.
   * @example
   * // Update or create a PaymentLine
   * const paymentLine = await prisma.paymentLine.upsert({
   *   create: {
   *     // ... data to create a PaymentLine
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PaymentLine we want to update
   *   }
   * })
   */
  upsert<T extends PaymentLineUpsertArgs>(args: Prisma.SelectSubset<T, PaymentLineUpsertArgs<ExtArgs>>): Prisma.Prisma__PaymentLineClient<runtime.Types.Result.GetResult<Prisma.$PaymentLinePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PaymentLines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLineCountArgs} args - Arguments to filter PaymentLines to count.
   * @example
   * // Count the number of PaymentLines
   * const count = await prisma.paymentLine.count({
   *   where: {
   *     // ... the filter for the PaymentLines we want to count
   *   }
   * })
  **/
  count<T extends PaymentLineCountArgs>(
    args?: Prisma.Subset<T, PaymentLineCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PaymentLineCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PaymentLine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLineAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PaymentLineAggregateArgs>(args: Prisma.Subset<T, PaymentLineAggregateArgs>): Prisma.PrismaPromise<GetPaymentLineAggregateType<T>>

  /**
   * Group by PaymentLine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLineGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PaymentLineGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PaymentLineGroupByArgs['orderBy'] }
      : { orderBy?: PaymentLineGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PaymentLineGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPaymentLineGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PaymentLine model
 */
readonly fields: PaymentLineFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PaymentLine.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PaymentLineClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  payment<T extends Prisma.PaymentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PaymentDefaultArgs<ExtArgs>>): Prisma.Prisma__PaymentClient<runtime.Types.Result.GetResult<Prisma.$PaymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PaymentLine model
 */
export interface PaymentLineFieldRefs {
  readonly id: Prisma.FieldRef<"PaymentLine", 'Int'>
  readonly paymentId: Prisma.FieldRef<"PaymentLine", 'Int'>
  readonly amount: Prisma.FieldRef<"PaymentLine", 'Float'>
  readonly title: Prisma.FieldRef<"PaymentLine", 'String'>
  readonly type: Prisma.FieldRef<"PaymentLine", 'String'>
  readonly numCheque: Prisma.FieldRef<"PaymentLine", 'String'>
}
    

// Custom InputTypes
/**
 * PaymentLine findUnique
 */
export type PaymentLineFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineInclude<ExtArgs> | null
  /**
   * Filter, which PaymentLine to fetch.
   */
  where: Prisma.PaymentLineWhereUniqueInput
}

/**
 * PaymentLine findUniqueOrThrow
 */
export type PaymentLineFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineInclude<ExtArgs> | null
  /**
   * Filter, which PaymentLine to fetch.
   */
  where: Prisma.PaymentLineWhereUniqueInput
}

/**
 * PaymentLine findFirst
 */
export type PaymentLineFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineInclude<ExtArgs> | null
  /**
   * Filter, which PaymentLine to fetch.
   */
  where?: Prisma.PaymentLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentLines to fetch.
   */
  orderBy?: Prisma.PaymentLineOrderByWithRelationInput | Prisma.PaymentLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PaymentLines.
   */
  cursor?: Prisma.PaymentLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaymentLines.
   */
  distinct?: Prisma.PaymentLineScalarFieldEnum | Prisma.PaymentLineScalarFieldEnum[]
}

/**
 * PaymentLine findFirstOrThrow
 */
export type PaymentLineFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineInclude<ExtArgs> | null
  /**
   * Filter, which PaymentLine to fetch.
   */
  where?: Prisma.PaymentLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentLines to fetch.
   */
  orderBy?: Prisma.PaymentLineOrderByWithRelationInput | Prisma.PaymentLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PaymentLines.
   */
  cursor?: Prisma.PaymentLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaymentLines.
   */
  distinct?: Prisma.PaymentLineScalarFieldEnum | Prisma.PaymentLineScalarFieldEnum[]
}

/**
 * PaymentLine findMany
 */
export type PaymentLineFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineInclude<ExtArgs> | null
  /**
   * Filter, which PaymentLines to fetch.
   */
  where?: Prisma.PaymentLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentLines to fetch.
   */
  orderBy?: Prisma.PaymentLineOrderByWithRelationInput | Prisma.PaymentLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PaymentLines.
   */
  cursor?: Prisma.PaymentLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentLines.
   */
  skip?: number
  distinct?: Prisma.PaymentLineScalarFieldEnum | Prisma.PaymentLineScalarFieldEnum[]
}

/**
 * PaymentLine create
 */
export type PaymentLineCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineInclude<ExtArgs> | null
  /**
   * The data needed to create a PaymentLine.
   */
  data: Prisma.XOR<Prisma.PaymentLineCreateInput, Prisma.PaymentLineUncheckedCreateInput>
}

/**
 * PaymentLine createMany
 */
export type PaymentLineCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PaymentLines.
   */
  data: Prisma.PaymentLineCreateManyInput | Prisma.PaymentLineCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PaymentLine createManyAndReturn
 */
export type PaymentLineCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * The data used to create many PaymentLines.
   */
  data: Prisma.PaymentLineCreateManyInput | Prisma.PaymentLineCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PaymentLine update
 */
export type PaymentLineUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineInclude<ExtArgs> | null
  /**
   * The data needed to update a PaymentLine.
   */
  data: Prisma.XOR<Prisma.PaymentLineUpdateInput, Prisma.PaymentLineUncheckedUpdateInput>
  /**
   * Choose, which PaymentLine to update.
   */
  where: Prisma.PaymentLineWhereUniqueInput
}

/**
 * PaymentLine updateMany
 */
export type PaymentLineUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PaymentLines.
   */
  data: Prisma.XOR<Prisma.PaymentLineUpdateManyMutationInput, Prisma.PaymentLineUncheckedUpdateManyInput>
  /**
   * Filter which PaymentLines to update
   */
  where?: Prisma.PaymentLineWhereInput
  /**
   * Limit how many PaymentLines to update.
   */
  limit?: number
}

/**
 * PaymentLine updateManyAndReturn
 */
export type PaymentLineUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * The data used to update PaymentLines.
   */
  data: Prisma.XOR<Prisma.PaymentLineUpdateManyMutationInput, Prisma.PaymentLineUncheckedUpdateManyInput>
  /**
   * Filter which PaymentLines to update
   */
  where?: Prisma.PaymentLineWhereInput
  /**
   * Limit how many PaymentLines to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PaymentLine upsert
 */
export type PaymentLineUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineInclude<ExtArgs> | null
  /**
   * The filter to search for the PaymentLine to update in case it exists.
   */
  where: Prisma.PaymentLineWhereUniqueInput
  /**
   * In case the PaymentLine found by the `where` argument doesn't exist, create a new PaymentLine with this data.
   */
  create: Prisma.XOR<Prisma.PaymentLineCreateInput, Prisma.PaymentLineUncheckedCreateInput>
  /**
   * In case the PaymentLine was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PaymentLineUpdateInput, Prisma.PaymentLineUncheckedUpdateInput>
}

/**
 * PaymentLine delete
 */
export type PaymentLineDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineInclude<ExtArgs> | null
  /**
   * Filter which PaymentLine to delete.
   */
  where: Prisma.PaymentLineWhereUniqueInput
}

/**
 * PaymentLine deleteMany
 */
export type PaymentLineDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PaymentLines to delete
   */
  where?: Prisma.PaymentLineWhereInput
  /**
   * Limit how many PaymentLines to delete.
   */
  limit?: number
}

/**
 * PaymentLine without action
 */
export type PaymentLineDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLine
   */
  select?: Prisma.PaymentLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLine
   */
  omit?: Prisma.PaymentLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLineInclude<ExtArgs> | null
}
