
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Planing` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Planing
 * 
 */
export type PlaningModel = runtime.Types.Result.DefaultSelection<Prisma.$PlaningPayload>

export type AggregatePlaning = {
  _count: PlaningCountAggregateOutputType | null
  _avg: PlaningAvgAggregateOutputType | null
  _sum: PlaningSumAggregateOutputType | null
  _min: PlaningMinAggregateOutputType | null
  _max: PlaningMaxAggregateOutputType | null
}

export type PlaningAvgAggregateOutputType = {
  id: number | null
  teacherId: number | null
  classId: number | null
}

export type PlaningSumAggregateOutputType = {
  id: number | null
  teacherId: number | null
  classId: number | null
}

export type PlaningMinAggregateOutputType = {
  id: number | null
  teacherId: number | null
  as: string | null
  name: string | null
  type: string | null
  datePlaning: Date | null
  description: string | null
  classId: number | null
}

export type PlaningMaxAggregateOutputType = {
  id: number | null
  teacherId: number | null
  as: string | null
  name: string | null
  type: string | null
  datePlaning: Date | null
  description: string | null
  classId: number | null
}

export type PlaningCountAggregateOutputType = {
  id: number
  teacherId: number
  as: number
  name: number
  type: number
  datePlaning: number
  description: number
  classId: number
  _all: number
}


export type PlaningAvgAggregateInputType = {
  id?: true
  teacherId?: true
  classId?: true
}

export type PlaningSumAggregateInputType = {
  id?: true
  teacherId?: true
  classId?: true
}

export type PlaningMinAggregateInputType = {
  id?: true
  teacherId?: true
  as?: true
  name?: true
  type?: true
  datePlaning?: true
  description?: true
  classId?: true
}

export type PlaningMaxAggregateInputType = {
  id?: true
  teacherId?: true
  as?: true
  name?: true
  type?: true
  datePlaning?: true
  description?: true
  classId?: true
}

export type PlaningCountAggregateInputType = {
  id?: true
  teacherId?: true
  as?: true
  name?: true
  type?: true
  datePlaning?: true
  description?: true
  classId?: true
  _all?: true
}

export type PlaningAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Planing to aggregate.
   */
  where?: Prisma.PlaningWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Planings to fetch.
   */
  orderBy?: Prisma.PlaningOrderByWithRelationInput | Prisma.PlaningOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlaningWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Planings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Planings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Planings
  **/
  _count?: true | PlaningCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PlaningAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PlaningSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlaningMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlaningMaxAggregateInputType
}

export type GetPlaningAggregateType<T extends PlaningAggregateArgs> = {
      [P in keyof T & keyof AggregatePlaning]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlaning[P]>
    : Prisma.GetScalarType<T[P], AggregatePlaning[P]>
}




export type PlaningGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlaningWhereInput
  orderBy?: Prisma.PlaningOrderByWithAggregationInput | Prisma.PlaningOrderByWithAggregationInput[]
  by: Prisma.PlaningScalarFieldEnum[] | Prisma.PlaningScalarFieldEnum
  having?: Prisma.PlaningScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlaningCountAggregateInputType | true
  _avg?: PlaningAvgAggregateInputType
  _sum?: PlaningSumAggregateInputType
  _min?: PlaningMinAggregateInputType
  _max?: PlaningMaxAggregateInputType
}

export type PlaningGroupByOutputType = {
  id: number
  teacherId: number | null
  as: string | null
  name: string | null
  type: string | null
  datePlaning: Date | null
  description: string | null
  classId: number | null
  _count: PlaningCountAggregateOutputType | null
  _avg: PlaningAvgAggregateOutputType | null
  _sum: PlaningSumAggregateOutputType | null
  _min: PlaningMinAggregateOutputType | null
  _max: PlaningMaxAggregateOutputType | null
}

type GetPlaningGroupByPayload<T extends PlaningGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlaningGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlaningGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlaningGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlaningGroupByOutputType[P]>
      }
    >
  >



export type PlaningWhereInput = {
  AND?: Prisma.PlaningWhereInput | Prisma.PlaningWhereInput[]
  OR?: Prisma.PlaningWhereInput[]
  NOT?: Prisma.PlaningWhereInput | Prisma.PlaningWhereInput[]
  id?: Prisma.IntFilter<"Planing"> | number
  teacherId?: Prisma.IntNullableFilter<"Planing"> | number | null
  as?: Prisma.StringNullableFilter<"Planing"> | string | null
  name?: Prisma.StringNullableFilter<"Planing"> | string | null
  type?: Prisma.StringNullableFilter<"Planing"> | string | null
  datePlaning?: Prisma.DateTimeNullableFilter<"Planing"> | Date | string | null
  description?: Prisma.StringNullableFilter<"Planing"> | string | null
  classId?: Prisma.IntNullableFilter<"Planing"> | number | null
  class?: Prisma.XOR<Prisma.ClassNullableScalarRelationFilter, Prisma.ClassWhereInput> | null
  teacher?: Prisma.XOR<Prisma.TeacherNullableScalarRelationFilter, Prisma.TeacherWhereInput> | null
  ressouces?: Prisma.RessouceListRelationFilter
  sessionEvaluations?: Prisma.SessionEvaluationListRelationFilter
}

export type PlaningOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  teacherId?: Prisma.SortOrderInput | Prisma.SortOrder
  as?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  datePlaning?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  classId?: Prisma.SortOrderInput | Prisma.SortOrder
  class?: Prisma.ClassOrderByWithRelationInput
  teacher?: Prisma.TeacherOrderByWithRelationInput
  ressouces?: Prisma.RessouceOrderByRelationAggregateInput
  sessionEvaluations?: Prisma.SessionEvaluationOrderByRelationAggregateInput
}

export type PlaningWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.PlaningWhereInput | Prisma.PlaningWhereInput[]
  OR?: Prisma.PlaningWhereInput[]
  NOT?: Prisma.PlaningWhereInput | Prisma.PlaningWhereInput[]
  teacherId?: Prisma.IntNullableFilter<"Planing"> | number | null
  as?: Prisma.StringNullableFilter<"Planing"> | string | null
  name?: Prisma.StringNullableFilter<"Planing"> | string | null
  type?: Prisma.StringNullableFilter<"Planing"> | string | null
  datePlaning?: Prisma.DateTimeNullableFilter<"Planing"> | Date | string | null
  description?: Prisma.StringNullableFilter<"Planing"> | string | null
  classId?: Prisma.IntNullableFilter<"Planing"> | number | null
  class?: Prisma.XOR<Prisma.ClassNullableScalarRelationFilter, Prisma.ClassWhereInput> | null
  teacher?: Prisma.XOR<Prisma.TeacherNullableScalarRelationFilter, Prisma.TeacherWhereInput> | null
  ressouces?: Prisma.RessouceListRelationFilter
  sessionEvaluations?: Prisma.SessionEvaluationListRelationFilter
}, "id">

export type PlaningOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  teacherId?: Prisma.SortOrderInput | Prisma.SortOrder
  as?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  datePlaning?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  classId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PlaningCountOrderByAggregateInput
  _avg?: Prisma.PlaningAvgOrderByAggregateInput
  _max?: Prisma.PlaningMaxOrderByAggregateInput
  _min?: Prisma.PlaningMinOrderByAggregateInput
  _sum?: Prisma.PlaningSumOrderByAggregateInput
}

export type PlaningScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlaningScalarWhereWithAggregatesInput | Prisma.PlaningScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlaningScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlaningScalarWhereWithAggregatesInput | Prisma.PlaningScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Planing"> | number
  teacherId?: Prisma.IntNullableWithAggregatesFilter<"Planing"> | number | null
  as?: Prisma.StringNullableWithAggregatesFilter<"Planing"> | string | null
  name?: Prisma.StringNullableWithAggregatesFilter<"Planing"> | string | null
  type?: Prisma.StringNullableWithAggregatesFilter<"Planing"> | string | null
  datePlaning?: Prisma.DateTimeNullableWithAggregatesFilter<"Planing"> | Date | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Planing"> | string | null
  classId?: Prisma.IntNullableWithAggregatesFilter<"Planing"> | number | null
}

export type PlaningCreateInput = {
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  class?: Prisma.ClassCreateNestedOneWithoutPlaningsInput
  teacher?: Prisma.TeacherCreateNestedOneWithoutPlaningsInput
  ressouces?: Prisma.RessouceCreateNestedManyWithoutPlaningInput
  sessionEvaluations?: Prisma.SessionEvaluationCreateNestedManyWithoutPlaningInput
}

export type PlaningUncheckedCreateInput = {
  id?: number
  teacherId?: number | null
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  classId?: number | null
  ressouces?: Prisma.RessouceUncheckedCreateNestedManyWithoutPlaningInput
  sessionEvaluations?: Prisma.SessionEvaluationUncheckedCreateNestedManyWithoutPlaningInput
}

export type PlaningUpdateInput = {
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.ClassUpdateOneWithoutPlaningsNestedInput
  teacher?: Prisma.TeacherUpdateOneWithoutPlaningsNestedInput
  ressouces?: Prisma.RessouceUpdateManyWithoutPlaningNestedInput
  sessionEvaluations?: Prisma.SessionEvaluationUpdateManyWithoutPlaningNestedInput
}

export type PlaningUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ressouces?: Prisma.RessouceUncheckedUpdateManyWithoutPlaningNestedInput
  sessionEvaluations?: Prisma.SessionEvaluationUncheckedUpdateManyWithoutPlaningNestedInput
}

export type PlaningCreateManyInput = {
  id?: number
  teacherId?: number | null
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  classId?: number | null
}

export type PlaningUpdateManyMutationInput = {
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PlaningUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type PlaningListRelationFilter = {
  every?: Prisma.PlaningWhereInput
  some?: Prisma.PlaningWhereInput
  none?: Prisma.PlaningWhereInput
}

export type PlaningOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PlaningCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  as?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  datePlaning?: Prisma.SortOrder
  description?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type PlaningAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type PlaningMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  as?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  datePlaning?: Prisma.SortOrder
  description?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type PlaningMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  as?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  datePlaning?: Prisma.SortOrder
  description?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type PlaningSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type PlaningScalarRelationFilter = {
  is?: Prisma.PlaningWhereInput
  isNot?: Prisma.PlaningWhereInput
}

export type PlaningNullableScalarRelationFilter = {
  is?: Prisma.PlaningWhereInput | null
  isNot?: Prisma.PlaningWhereInput | null
}

export type PlaningCreateNestedManyWithoutTeacherInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutTeacherInput, Prisma.PlaningUncheckedCreateWithoutTeacherInput> | Prisma.PlaningCreateWithoutTeacherInput[] | Prisma.PlaningUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutTeacherInput | Prisma.PlaningCreateOrConnectWithoutTeacherInput[]
  createMany?: Prisma.PlaningCreateManyTeacherInputEnvelope
  connect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
}

export type PlaningUncheckedCreateNestedManyWithoutTeacherInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutTeacherInput, Prisma.PlaningUncheckedCreateWithoutTeacherInput> | Prisma.PlaningCreateWithoutTeacherInput[] | Prisma.PlaningUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutTeacherInput | Prisma.PlaningCreateOrConnectWithoutTeacherInput[]
  createMany?: Prisma.PlaningCreateManyTeacherInputEnvelope
  connect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
}

export type PlaningUpdateManyWithoutTeacherNestedInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutTeacherInput, Prisma.PlaningUncheckedCreateWithoutTeacherInput> | Prisma.PlaningCreateWithoutTeacherInput[] | Prisma.PlaningUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutTeacherInput | Prisma.PlaningCreateOrConnectWithoutTeacherInput[]
  upsert?: Prisma.PlaningUpsertWithWhereUniqueWithoutTeacherInput | Prisma.PlaningUpsertWithWhereUniqueWithoutTeacherInput[]
  createMany?: Prisma.PlaningCreateManyTeacherInputEnvelope
  set?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  disconnect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  delete?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  connect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  update?: Prisma.PlaningUpdateWithWhereUniqueWithoutTeacherInput | Prisma.PlaningUpdateWithWhereUniqueWithoutTeacherInput[]
  updateMany?: Prisma.PlaningUpdateManyWithWhereWithoutTeacherInput | Prisma.PlaningUpdateManyWithWhereWithoutTeacherInput[]
  deleteMany?: Prisma.PlaningScalarWhereInput | Prisma.PlaningScalarWhereInput[]
}

export type PlaningUncheckedUpdateManyWithoutTeacherNestedInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutTeacherInput, Prisma.PlaningUncheckedCreateWithoutTeacherInput> | Prisma.PlaningCreateWithoutTeacherInput[] | Prisma.PlaningUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutTeacherInput | Prisma.PlaningCreateOrConnectWithoutTeacherInput[]
  upsert?: Prisma.PlaningUpsertWithWhereUniqueWithoutTeacherInput | Prisma.PlaningUpsertWithWhereUniqueWithoutTeacherInput[]
  createMany?: Prisma.PlaningCreateManyTeacherInputEnvelope
  set?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  disconnect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  delete?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  connect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  update?: Prisma.PlaningUpdateWithWhereUniqueWithoutTeacherInput | Prisma.PlaningUpdateWithWhereUniqueWithoutTeacherInput[]
  updateMany?: Prisma.PlaningUpdateManyWithWhereWithoutTeacherInput | Prisma.PlaningUpdateManyWithWhereWithoutTeacherInput[]
  deleteMany?: Prisma.PlaningScalarWhereInput | Prisma.PlaningScalarWhereInput[]
}

export type PlaningCreateNestedManyWithoutClassInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutClassInput, Prisma.PlaningUncheckedCreateWithoutClassInput> | Prisma.PlaningCreateWithoutClassInput[] | Prisma.PlaningUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutClassInput | Prisma.PlaningCreateOrConnectWithoutClassInput[]
  createMany?: Prisma.PlaningCreateManyClassInputEnvelope
  connect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
}

export type PlaningUncheckedCreateNestedManyWithoutClassInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutClassInput, Prisma.PlaningUncheckedCreateWithoutClassInput> | Prisma.PlaningCreateWithoutClassInput[] | Prisma.PlaningUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutClassInput | Prisma.PlaningCreateOrConnectWithoutClassInput[]
  createMany?: Prisma.PlaningCreateManyClassInputEnvelope
  connect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
}

export type PlaningUpdateManyWithoutClassNestedInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutClassInput, Prisma.PlaningUncheckedCreateWithoutClassInput> | Prisma.PlaningCreateWithoutClassInput[] | Prisma.PlaningUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutClassInput | Prisma.PlaningCreateOrConnectWithoutClassInput[]
  upsert?: Prisma.PlaningUpsertWithWhereUniqueWithoutClassInput | Prisma.PlaningUpsertWithWhereUniqueWithoutClassInput[]
  createMany?: Prisma.PlaningCreateManyClassInputEnvelope
  set?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  disconnect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  delete?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  connect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  update?: Prisma.PlaningUpdateWithWhereUniqueWithoutClassInput | Prisma.PlaningUpdateWithWhereUniqueWithoutClassInput[]
  updateMany?: Prisma.PlaningUpdateManyWithWhereWithoutClassInput | Prisma.PlaningUpdateManyWithWhereWithoutClassInput[]
  deleteMany?: Prisma.PlaningScalarWhereInput | Prisma.PlaningScalarWhereInput[]
}

export type PlaningUncheckedUpdateManyWithoutClassNestedInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutClassInput, Prisma.PlaningUncheckedCreateWithoutClassInput> | Prisma.PlaningCreateWithoutClassInput[] | Prisma.PlaningUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutClassInput | Prisma.PlaningCreateOrConnectWithoutClassInput[]
  upsert?: Prisma.PlaningUpsertWithWhereUniqueWithoutClassInput | Prisma.PlaningUpsertWithWhereUniqueWithoutClassInput[]
  createMany?: Prisma.PlaningCreateManyClassInputEnvelope
  set?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  disconnect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  delete?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  connect?: Prisma.PlaningWhereUniqueInput | Prisma.PlaningWhereUniqueInput[]
  update?: Prisma.PlaningUpdateWithWhereUniqueWithoutClassInput | Prisma.PlaningUpdateWithWhereUniqueWithoutClassInput[]
  updateMany?: Prisma.PlaningUpdateManyWithWhereWithoutClassInput | Prisma.PlaningUpdateManyWithWhereWithoutClassInput[]
  deleteMany?: Prisma.PlaningScalarWhereInput | Prisma.PlaningScalarWhereInput[]
}

export type PlaningCreateNestedOneWithoutSessionEvaluationsInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutSessionEvaluationsInput, Prisma.PlaningUncheckedCreateWithoutSessionEvaluationsInput>
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutSessionEvaluationsInput
  connect?: Prisma.PlaningWhereUniqueInput
}

export type PlaningUpdateOneRequiredWithoutSessionEvaluationsNestedInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutSessionEvaluationsInput, Prisma.PlaningUncheckedCreateWithoutSessionEvaluationsInput>
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutSessionEvaluationsInput
  upsert?: Prisma.PlaningUpsertWithoutSessionEvaluationsInput
  connect?: Prisma.PlaningWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlaningUpdateToOneWithWhereWithoutSessionEvaluationsInput, Prisma.PlaningUpdateWithoutSessionEvaluationsInput>, Prisma.PlaningUncheckedUpdateWithoutSessionEvaluationsInput>
}

export type PlaningCreateNestedOneWithoutRessoucesInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutRessoucesInput, Prisma.PlaningUncheckedCreateWithoutRessoucesInput>
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutRessoucesInput
  connect?: Prisma.PlaningWhereUniqueInput
}

export type PlaningUpdateOneWithoutRessoucesNestedInput = {
  create?: Prisma.XOR<Prisma.PlaningCreateWithoutRessoucesInput, Prisma.PlaningUncheckedCreateWithoutRessoucesInput>
  connectOrCreate?: Prisma.PlaningCreateOrConnectWithoutRessoucesInput
  upsert?: Prisma.PlaningUpsertWithoutRessoucesInput
  disconnect?: Prisma.PlaningWhereInput | boolean
  delete?: Prisma.PlaningWhereInput | boolean
  connect?: Prisma.PlaningWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PlaningUpdateToOneWithWhereWithoutRessoucesInput, Prisma.PlaningUpdateWithoutRessoucesInput>, Prisma.PlaningUncheckedUpdateWithoutRessoucesInput>
}

export type PlaningCreateWithoutTeacherInput = {
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  class?: Prisma.ClassCreateNestedOneWithoutPlaningsInput
  ressouces?: Prisma.RessouceCreateNestedManyWithoutPlaningInput
  sessionEvaluations?: Prisma.SessionEvaluationCreateNestedManyWithoutPlaningInput
}

export type PlaningUncheckedCreateWithoutTeacherInput = {
  id?: number
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  classId?: number | null
  ressouces?: Prisma.RessouceUncheckedCreateNestedManyWithoutPlaningInput
  sessionEvaluations?: Prisma.SessionEvaluationUncheckedCreateNestedManyWithoutPlaningInput
}

export type PlaningCreateOrConnectWithoutTeacherInput = {
  where: Prisma.PlaningWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaningCreateWithoutTeacherInput, Prisma.PlaningUncheckedCreateWithoutTeacherInput>
}

export type PlaningCreateManyTeacherInputEnvelope = {
  data: Prisma.PlaningCreateManyTeacherInput | Prisma.PlaningCreateManyTeacherInput[]
  skipDuplicates?: boolean
}

export type PlaningUpsertWithWhereUniqueWithoutTeacherInput = {
  where: Prisma.PlaningWhereUniqueInput
  update: Prisma.XOR<Prisma.PlaningUpdateWithoutTeacherInput, Prisma.PlaningUncheckedUpdateWithoutTeacherInput>
  create: Prisma.XOR<Prisma.PlaningCreateWithoutTeacherInput, Prisma.PlaningUncheckedCreateWithoutTeacherInput>
}

export type PlaningUpdateWithWhereUniqueWithoutTeacherInput = {
  where: Prisma.PlaningWhereUniqueInput
  data: Prisma.XOR<Prisma.PlaningUpdateWithoutTeacherInput, Prisma.PlaningUncheckedUpdateWithoutTeacherInput>
}

export type PlaningUpdateManyWithWhereWithoutTeacherInput = {
  where: Prisma.PlaningScalarWhereInput
  data: Prisma.XOR<Prisma.PlaningUpdateManyMutationInput, Prisma.PlaningUncheckedUpdateManyWithoutTeacherInput>
}

export type PlaningScalarWhereInput = {
  AND?: Prisma.PlaningScalarWhereInput | Prisma.PlaningScalarWhereInput[]
  OR?: Prisma.PlaningScalarWhereInput[]
  NOT?: Prisma.PlaningScalarWhereInput | Prisma.PlaningScalarWhereInput[]
  id?: Prisma.IntFilter<"Planing"> | number
  teacherId?: Prisma.IntNullableFilter<"Planing"> | number | null
  as?: Prisma.StringNullableFilter<"Planing"> | string | null
  name?: Prisma.StringNullableFilter<"Planing"> | string | null
  type?: Prisma.StringNullableFilter<"Planing"> | string | null
  datePlaning?: Prisma.DateTimeNullableFilter<"Planing"> | Date | string | null
  description?: Prisma.StringNullableFilter<"Planing"> | string | null
  classId?: Prisma.IntNullableFilter<"Planing"> | number | null
}

export type PlaningCreateWithoutClassInput = {
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  teacher?: Prisma.TeacherCreateNestedOneWithoutPlaningsInput
  ressouces?: Prisma.RessouceCreateNestedManyWithoutPlaningInput
  sessionEvaluations?: Prisma.SessionEvaluationCreateNestedManyWithoutPlaningInput
}

export type PlaningUncheckedCreateWithoutClassInput = {
  id?: number
  teacherId?: number | null
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  ressouces?: Prisma.RessouceUncheckedCreateNestedManyWithoutPlaningInput
  sessionEvaluations?: Prisma.SessionEvaluationUncheckedCreateNestedManyWithoutPlaningInput
}

export type PlaningCreateOrConnectWithoutClassInput = {
  where: Prisma.PlaningWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaningCreateWithoutClassInput, Prisma.PlaningUncheckedCreateWithoutClassInput>
}

export type PlaningCreateManyClassInputEnvelope = {
  data: Prisma.PlaningCreateManyClassInput | Prisma.PlaningCreateManyClassInput[]
  skipDuplicates?: boolean
}

export type PlaningUpsertWithWhereUniqueWithoutClassInput = {
  where: Prisma.PlaningWhereUniqueInput
  update: Prisma.XOR<Prisma.PlaningUpdateWithoutClassInput, Prisma.PlaningUncheckedUpdateWithoutClassInput>
  create: Prisma.XOR<Prisma.PlaningCreateWithoutClassInput, Prisma.PlaningUncheckedCreateWithoutClassInput>
}

export type PlaningUpdateWithWhereUniqueWithoutClassInput = {
  where: Prisma.PlaningWhereUniqueInput
  data: Prisma.XOR<Prisma.PlaningUpdateWithoutClassInput, Prisma.PlaningUncheckedUpdateWithoutClassInput>
}

export type PlaningUpdateManyWithWhereWithoutClassInput = {
  where: Prisma.PlaningScalarWhereInput
  data: Prisma.XOR<Prisma.PlaningUpdateManyMutationInput, Prisma.PlaningUncheckedUpdateManyWithoutClassInput>
}

export type PlaningCreateWithoutSessionEvaluationsInput = {
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  class?: Prisma.ClassCreateNestedOneWithoutPlaningsInput
  teacher?: Prisma.TeacherCreateNestedOneWithoutPlaningsInput
  ressouces?: Prisma.RessouceCreateNestedManyWithoutPlaningInput
}

export type PlaningUncheckedCreateWithoutSessionEvaluationsInput = {
  id?: number
  teacherId?: number | null
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  classId?: number | null
  ressouces?: Prisma.RessouceUncheckedCreateNestedManyWithoutPlaningInput
}

export type PlaningCreateOrConnectWithoutSessionEvaluationsInput = {
  where: Prisma.PlaningWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaningCreateWithoutSessionEvaluationsInput, Prisma.PlaningUncheckedCreateWithoutSessionEvaluationsInput>
}

export type PlaningUpsertWithoutSessionEvaluationsInput = {
  update: Prisma.XOR<Prisma.PlaningUpdateWithoutSessionEvaluationsInput, Prisma.PlaningUncheckedUpdateWithoutSessionEvaluationsInput>
  create: Prisma.XOR<Prisma.PlaningCreateWithoutSessionEvaluationsInput, Prisma.PlaningUncheckedCreateWithoutSessionEvaluationsInput>
  where?: Prisma.PlaningWhereInput
}

export type PlaningUpdateToOneWithWhereWithoutSessionEvaluationsInput = {
  where?: Prisma.PlaningWhereInput
  data: Prisma.XOR<Prisma.PlaningUpdateWithoutSessionEvaluationsInput, Prisma.PlaningUncheckedUpdateWithoutSessionEvaluationsInput>
}

export type PlaningUpdateWithoutSessionEvaluationsInput = {
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.ClassUpdateOneWithoutPlaningsNestedInput
  teacher?: Prisma.TeacherUpdateOneWithoutPlaningsNestedInput
  ressouces?: Prisma.RessouceUpdateManyWithoutPlaningNestedInput
}

export type PlaningUncheckedUpdateWithoutSessionEvaluationsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ressouces?: Prisma.RessouceUncheckedUpdateManyWithoutPlaningNestedInput
}

export type PlaningCreateWithoutRessoucesInput = {
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  class?: Prisma.ClassCreateNestedOneWithoutPlaningsInput
  teacher?: Prisma.TeacherCreateNestedOneWithoutPlaningsInput
  sessionEvaluations?: Prisma.SessionEvaluationCreateNestedManyWithoutPlaningInput
}

export type PlaningUncheckedCreateWithoutRessoucesInput = {
  id?: number
  teacherId?: number | null
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  classId?: number | null
  sessionEvaluations?: Prisma.SessionEvaluationUncheckedCreateNestedManyWithoutPlaningInput
}

export type PlaningCreateOrConnectWithoutRessoucesInput = {
  where: Prisma.PlaningWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaningCreateWithoutRessoucesInput, Prisma.PlaningUncheckedCreateWithoutRessoucesInput>
}

export type PlaningUpsertWithoutRessoucesInput = {
  update: Prisma.XOR<Prisma.PlaningUpdateWithoutRessoucesInput, Prisma.PlaningUncheckedUpdateWithoutRessoucesInput>
  create: Prisma.XOR<Prisma.PlaningCreateWithoutRessoucesInput, Prisma.PlaningUncheckedCreateWithoutRessoucesInput>
  where?: Prisma.PlaningWhereInput
}

export type PlaningUpdateToOneWithWhereWithoutRessoucesInput = {
  where?: Prisma.PlaningWhereInput
  data: Prisma.XOR<Prisma.PlaningUpdateWithoutRessoucesInput, Prisma.PlaningUncheckedUpdateWithoutRessoucesInput>
}

export type PlaningUpdateWithoutRessoucesInput = {
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.ClassUpdateOneWithoutPlaningsNestedInput
  teacher?: Prisma.TeacherUpdateOneWithoutPlaningsNestedInput
  sessionEvaluations?: Prisma.SessionEvaluationUpdateManyWithoutPlaningNestedInput
}

export type PlaningUncheckedUpdateWithoutRessoucesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sessionEvaluations?: Prisma.SessionEvaluationUncheckedUpdateManyWithoutPlaningNestedInput
}

export type PlaningCreateManyTeacherInput = {
  id?: number
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
  classId?: number | null
}

export type PlaningUpdateWithoutTeacherInput = {
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.ClassUpdateOneWithoutPlaningsNestedInput
  ressouces?: Prisma.RessouceUpdateManyWithoutPlaningNestedInput
  sessionEvaluations?: Prisma.SessionEvaluationUpdateManyWithoutPlaningNestedInput
}

export type PlaningUncheckedUpdateWithoutTeacherInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ressouces?: Prisma.RessouceUncheckedUpdateManyWithoutPlaningNestedInput
  sessionEvaluations?: Prisma.SessionEvaluationUncheckedUpdateManyWithoutPlaningNestedInput
}

export type PlaningUncheckedUpdateManyWithoutTeacherInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type PlaningCreateManyClassInput = {
  id?: number
  teacherId?: number | null
  as?: string | null
  name?: string | null
  type?: string | null
  datePlaning?: Date | string | null
  description?: string | null
}

export type PlaningUpdateWithoutClassInput = {
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  teacher?: Prisma.TeacherUpdateOneWithoutPlaningsNestedInput
  ressouces?: Prisma.RessouceUpdateManyWithoutPlaningNestedInput
  sessionEvaluations?: Prisma.SessionEvaluationUpdateManyWithoutPlaningNestedInput
}

export type PlaningUncheckedUpdateWithoutClassInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ressouces?: Prisma.RessouceUncheckedUpdateManyWithoutPlaningNestedInput
  sessionEvaluations?: Prisma.SessionEvaluationUncheckedUpdateManyWithoutPlaningNestedInput
}

export type PlaningUncheckedUpdateManyWithoutClassInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  teacherId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  as?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  datePlaning?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type PlaningCountOutputType
 */

export type PlaningCountOutputType = {
  ressouces: number
  sessionEvaluations: number
}

export type PlaningCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ressouces?: boolean | PlaningCountOutputTypeCountRessoucesArgs
  sessionEvaluations?: boolean | PlaningCountOutputTypeCountSessionEvaluationsArgs
}

/**
 * PlaningCountOutputType without action
 */
export type PlaningCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaningCountOutputType
   */
  select?: Prisma.PlaningCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PlaningCountOutputType without action
 */
export type PlaningCountOutputTypeCountRessoucesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RessouceWhereInput
}

/**
 * PlaningCountOutputType without action
 */
export type PlaningCountOutputTypeCountSessionEvaluationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionEvaluationWhereInput
}


export type PlaningSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teacherId?: boolean
  as?: boolean
  name?: boolean
  type?: boolean
  datePlaning?: boolean
  description?: boolean
  classId?: boolean
  class?: boolean | Prisma.Planing$classArgs<ExtArgs>
  teacher?: boolean | Prisma.Planing$teacherArgs<ExtArgs>
  ressouces?: boolean | Prisma.Planing$ressoucesArgs<ExtArgs>
  sessionEvaluations?: boolean | Prisma.Planing$sessionEvaluationsArgs<ExtArgs>
  _count?: boolean | Prisma.PlaningCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["planing"]>

export type PlaningSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teacherId?: boolean
  as?: boolean
  name?: boolean
  type?: boolean
  datePlaning?: boolean
  description?: boolean
  classId?: boolean
  class?: boolean | Prisma.Planing$classArgs<ExtArgs>
  teacher?: boolean | Prisma.Planing$teacherArgs<ExtArgs>
}, ExtArgs["result"]["planing"]>

export type PlaningSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teacherId?: boolean
  as?: boolean
  name?: boolean
  type?: boolean
  datePlaning?: boolean
  description?: boolean
  classId?: boolean
  class?: boolean | Prisma.Planing$classArgs<ExtArgs>
  teacher?: boolean | Prisma.Planing$teacherArgs<ExtArgs>
}, ExtArgs["result"]["planing"]>

export type PlaningSelectScalar = {
  id?: boolean
  teacherId?: boolean
  as?: boolean
  name?: boolean
  type?: boolean
  datePlaning?: boolean
  description?: boolean
  classId?: boolean
}

export type PlaningOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "teacherId" | "as" | "name" | "type" | "datePlaning" | "description" | "classId", ExtArgs["result"]["planing"]>
export type PlaningInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.Planing$classArgs<ExtArgs>
  teacher?: boolean | Prisma.Planing$teacherArgs<ExtArgs>
  ressouces?: boolean | Prisma.Planing$ressoucesArgs<ExtArgs>
  sessionEvaluations?: boolean | Prisma.Planing$sessionEvaluationsArgs<ExtArgs>
  _count?: boolean | Prisma.PlaningCountOutputTypeDefaultArgs<ExtArgs>
}
export type PlaningIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.Planing$classArgs<ExtArgs>
  teacher?: boolean | Prisma.Planing$teacherArgs<ExtArgs>
}
export type PlaningIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.Planing$classArgs<ExtArgs>
  teacher?: boolean | Prisma.Planing$teacherArgs<ExtArgs>
}

export type $PlaningPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Planing"
  objects: {
    class: Prisma.$ClassPayload<ExtArgs> | null
    teacher: Prisma.$TeacherPayload<ExtArgs> | null
    ressouces: Prisma.$RessoucePayload<ExtArgs>[]
    sessionEvaluations: Prisma.$SessionEvaluationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    teacherId: number | null
    as: string | null
    name: string | null
    type: string | null
    datePlaning: Date | null
    description: string | null
    classId: number | null
  }, ExtArgs["result"]["planing"]>
  composites: {}
}

export type PlaningGetPayload<S extends boolean | null | undefined | PlaningDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlaningPayload, S>

export type PlaningCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlaningFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlaningCountAggregateInputType | true
  }

export interface PlaningDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Planing'], meta: { name: 'Planing' } }
  /**
   * Find zero or one Planing that matches the filter.
   * @param {PlaningFindUniqueArgs} args - Arguments to find a Planing
   * @example
   * // Get one Planing
   * const planing = await prisma.planing.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlaningFindUniqueArgs>(args: Prisma.SelectSubset<T, PlaningFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlaningClient<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Planing that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlaningFindUniqueOrThrowArgs} args - Arguments to find a Planing
   * @example
   * // Get one Planing
   * const planing = await prisma.planing.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlaningFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlaningFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaningClient<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Planing that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaningFindFirstArgs} args - Arguments to find a Planing
   * @example
   * // Get one Planing
   * const planing = await prisma.planing.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlaningFindFirstArgs>(args?: Prisma.SelectSubset<T, PlaningFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlaningClient<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Planing that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaningFindFirstOrThrowArgs} args - Arguments to find a Planing
   * @example
   * // Get one Planing
   * const planing = await prisma.planing.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlaningFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlaningFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaningClient<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Planings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaningFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Planings
   * const planings = await prisma.planing.findMany()
   * 
   * // Get first 10 Planings
   * const planings = await prisma.planing.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const planingWithIdOnly = await prisma.planing.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlaningFindManyArgs>(args?: Prisma.SelectSubset<T, PlaningFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Planing.
   * @param {PlaningCreateArgs} args - Arguments to create a Planing.
   * @example
   * // Create one Planing
   * const Planing = await prisma.planing.create({
   *   data: {
   *     // ... data to create a Planing
   *   }
   * })
   * 
   */
  create<T extends PlaningCreateArgs>(args: Prisma.SelectSubset<T, PlaningCreateArgs<ExtArgs>>): Prisma.Prisma__PlaningClient<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Planings.
   * @param {PlaningCreateManyArgs} args - Arguments to create many Planings.
   * @example
   * // Create many Planings
   * const planing = await prisma.planing.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlaningCreateManyArgs>(args?: Prisma.SelectSubset<T, PlaningCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Planings and returns the data saved in the database.
   * @param {PlaningCreateManyAndReturnArgs} args - Arguments to create many Planings.
   * @example
   * // Create many Planings
   * const planing = await prisma.planing.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Planings and only return the `id`
   * const planingWithIdOnly = await prisma.planing.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlaningCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlaningCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Planing.
   * @param {PlaningDeleteArgs} args - Arguments to delete one Planing.
   * @example
   * // Delete one Planing
   * const Planing = await prisma.planing.delete({
   *   where: {
   *     // ... filter to delete one Planing
   *   }
   * })
   * 
   */
  delete<T extends PlaningDeleteArgs>(args: Prisma.SelectSubset<T, PlaningDeleteArgs<ExtArgs>>): Prisma.Prisma__PlaningClient<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Planing.
   * @param {PlaningUpdateArgs} args - Arguments to update one Planing.
   * @example
   * // Update one Planing
   * const planing = await prisma.planing.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlaningUpdateArgs>(args: Prisma.SelectSubset<T, PlaningUpdateArgs<ExtArgs>>): Prisma.Prisma__PlaningClient<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Planings.
   * @param {PlaningDeleteManyArgs} args - Arguments to filter Planings to delete.
   * @example
   * // Delete a few Planings
   * const { count } = await prisma.planing.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlaningDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlaningDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Planings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaningUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Planings
   * const planing = await prisma.planing.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlaningUpdateManyArgs>(args: Prisma.SelectSubset<T, PlaningUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Planings and returns the data updated in the database.
   * @param {PlaningUpdateManyAndReturnArgs} args - Arguments to update many Planings.
   * @example
   * // Update many Planings
   * const planing = await prisma.planing.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Planings and only return the `id`
   * const planingWithIdOnly = await prisma.planing.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlaningUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlaningUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Planing.
   * @param {PlaningUpsertArgs} args - Arguments to update or create a Planing.
   * @example
   * // Update or create a Planing
   * const planing = await prisma.planing.upsert({
   *   create: {
   *     // ... data to create a Planing
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Planing we want to update
   *   }
   * })
   */
  upsert<T extends PlaningUpsertArgs>(args: Prisma.SelectSubset<T, PlaningUpsertArgs<ExtArgs>>): Prisma.Prisma__PlaningClient<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Planings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaningCountArgs} args - Arguments to filter Planings to count.
   * @example
   * // Count the number of Planings
   * const count = await prisma.planing.count({
   *   where: {
   *     // ... the filter for the Planings we want to count
   *   }
   * })
  **/
  count<T extends PlaningCountArgs>(
    args?: Prisma.Subset<T, PlaningCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlaningCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Planing.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaningAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlaningAggregateArgs>(args: Prisma.Subset<T, PlaningAggregateArgs>): Prisma.PrismaPromise<GetPlaningAggregateType<T>>

  /**
   * Group by Planing.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaningGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlaningGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlaningGroupByArgs['orderBy'] }
      : { orderBy?: PlaningGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlaningGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlaningGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Planing model
 */
readonly fields: PlaningFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Planing.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlaningClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  class<T extends Prisma.Planing$classArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Planing$classArgs<ExtArgs>>): Prisma.Prisma__ClassClient<runtime.Types.Result.GetResult<Prisma.$ClassPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  teacher<T extends Prisma.Planing$teacherArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Planing$teacherArgs<ExtArgs>>): Prisma.Prisma__TeacherClient<runtime.Types.Result.GetResult<Prisma.$TeacherPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  ressouces<T extends Prisma.Planing$ressoucesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Planing$ressoucesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  sessionEvaluations<T extends Prisma.Planing$sessionEvaluationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Planing$sessionEvaluationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionEvaluationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Planing model
 */
export interface PlaningFieldRefs {
  readonly id: Prisma.FieldRef<"Planing", 'Int'>
  readonly teacherId: Prisma.FieldRef<"Planing", 'Int'>
  readonly as: Prisma.FieldRef<"Planing", 'String'>
  readonly name: Prisma.FieldRef<"Planing", 'String'>
  readonly type: Prisma.FieldRef<"Planing", 'String'>
  readonly datePlaning: Prisma.FieldRef<"Planing", 'DateTime'>
  readonly description: Prisma.FieldRef<"Planing", 'String'>
  readonly classId: Prisma.FieldRef<"Planing", 'Int'>
}
    

// Custom InputTypes
/**
 * Planing findUnique
 */
export type PlaningFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
  /**
   * Filter, which Planing to fetch.
   */
  where: Prisma.PlaningWhereUniqueInput
}

/**
 * Planing findUniqueOrThrow
 */
export type PlaningFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
  /**
   * Filter, which Planing to fetch.
   */
  where: Prisma.PlaningWhereUniqueInput
}

/**
 * Planing findFirst
 */
export type PlaningFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
  /**
   * Filter, which Planing to fetch.
   */
  where?: Prisma.PlaningWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Planings to fetch.
   */
  orderBy?: Prisma.PlaningOrderByWithRelationInput | Prisma.PlaningOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Planings.
   */
  cursor?: Prisma.PlaningWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Planings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Planings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Planings.
   */
  distinct?: Prisma.PlaningScalarFieldEnum | Prisma.PlaningScalarFieldEnum[]
}

/**
 * Planing findFirstOrThrow
 */
export type PlaningFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
  /**
   * Filter, which Planing to fetch.
   */
  where?: Prisma.PlaningWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Planings to fetch.
   */
  orderBy?: Prisma.PlaningOrderByWithRelationInput | Prisma.PlaningOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Planings.
   */
  cursor?: Prisma.PlaningWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Planings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Planings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Planings.
   */
  distinct?: Prisma.PlaningScalarFieldEnum | Prisma.PlaningScalarFieldEnum[]
}

/**
 * Planing findMany
 */
export type PlaningFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
  /**
   * Filter, which Planings to fetch.
   */
  where?: Prisma.PlaningWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Planings to fetch.
   */
  orderBy?: Prisma.PlaningOrderByWithRelationInput | Prisma.PlaningOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Planings.
   */
  cursor?: Prisma.PlaningWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Planings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Planings.
   */
  skip?: number
  distinct?: Prisma.PlaningScalarFieldEnum | Prisma.PlaningScalarFieldEnum[]
}

/**
 * Planing create
 */
export type PlaningCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
  /**
   * The data needed to create a Planing.
   */
  data?: Prisma.XOR<Prisma.PlaningCreateInput, Prisma.PlaningUncheckedCreateInput>
}

/**
 * Planing createMany
 */
export type PlaningCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Planings.
   */
  data: Prisma.PlaningCreateManyInput | Prisma.PlaningCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Planing createManyAndReturn
 */
export type PlaningCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * The data used to create many Planings.
   */
  data: Prisma.PlaningCreateManyInput | Prisma.PlaningCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Planing update
 */
export type PlaningUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
  /**
   * The data needed to update a Planing.
   */
  data: Prisma.XOR<Prisma.PlaningUpdateInput, Prisma.PlaningUncheckedUpdateInput>
  /**
   * Choose, which Planing to update.
   */
  where: Prisma.PlaningWhereUniqueInput
}

/**
 * Planing updateMany
 */
export type PlaningUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Planings.
   */
  data: Prisma.XOR<Prisma.PlaningUpdateManyMutationInput, Prisma.PlaningUncheckedUpdateManyInput>
  /**
   * Filter which Planings to update
   */
  where?: Prisma.PlaningWhereInput
  /**
   * Limit how many Planings to update.
   */
  limit?: number
}

/**
 * Planing updateManyAndReturn
 */
export type PlaningUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * The data used to update Planings.
   */
  data: Prisma.XOR<Prisma.PlaningUpdateManyMutationInput, Prisma.PlaningUncheckedUpdateManyInput>
  /**
   * Filter which Planings to update
   */
  where?: Prisma.PlaningWhereInput
  /**
   * Limit how many Planings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Planing upsert
 */
export type PlaningUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
  /**
   * The filter to search for the Planing to update in case it exists.
   */
  where: Prisma.PlaningWhereUniqueInput
  /**
   * In case the Planing found by the `where` argument doesn't exist, create a new Planing with this data.
   */
  create: Prisma.XOR<Prisma.PlaningCreateInput, Prisma.PlaningUncheckedCreateInput>
  /**
   * In case the Planing was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlaningUpdateInput, Prisma.PlaningUncheckedUpdateInput>
}

/**
 * Planing delete
 */
export type PlaningDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
  /**
   * Filter which Planing to delete.
   */
  where: Prisma.PlaningWhereUniqueInput
}

/**
 * Planing deleteMany
 */
export type PlaningDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Planings to delete
   */
  where?: Prisma.PlaningWhereInput
  /**
   * Limit how many Planings to delete.
   */
  limit?: number
}

/**
 * Planing.class
 */
export type Planing$classArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Class
   */
  select?: Prisma.ClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Class
   */
  omit?: Prisma.ClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClassInclude<ExtArgs> | null
  where?: Prisma.ClassWhereInput
}

/**
 * Planing.teacher
 */
export type Planing$teacherArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Teacher
   */
  select?: Prisma.TeacherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Teacher
   */
  omit?: Prisma.TeacherOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeacherInclude<ExtArgs> | null
  where?: Prisma.TeacherWhereInput
}

/**
 * Planing.ressouces
 */
export type Planing$ressoucesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
  where?: Prisma.RessouceWhereInput
  orderBy?: Prisma.RessouceOrderByWithRelationInput | Prisma.RessouceOrderByWithRelationInput[]
  cursor?: Prisma.RessouceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RessouceScalarFieldEnum | Prisma.RessouceScalarFieldEnum[]
}

/**
 * Planing.sessionEvaluations
 */
export type Planing$sessionEvaluationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionEvaluation
   */
  select?: Prisma.SessionEvaluationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionEvaluation
   */
  omit?: Prisma.SessionEvaluationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionEvaluationInclude<ExtArgs> | null
  where?: Prisma.SessionEvaluationWhereInput
  orderBy?: Prisma.SessionEvaluationOrderByWithRelationInput | Prisma.SessionEvaluationOrderByWithRelationInput[]
  cursor?: Prisma.SessionEvaluationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionEvaluationScalarFieldEnum | Prisma.SessionEvaluationScalarFieldEnum[]
}

/**
 * Planing without action
 */
export type PlaningDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
}
