
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Ressouce` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Ressouce
 * 
 */
export type RessouceModel = runtime.Types.Result.DefaultSelection<Prisma.$RessoucePayload>

export type AggregateRessouce = {
  _count: RessouceCountAggregateOutputType | null
  _avg: RessouceAvgAggregateOutputType | null
  _sum: RessouceSumAggregateOutputType | null
  _min: RessouceMinAggregateOutputType | null
  _max: RessouceMaxAggregateOutputType | null
}

export type RessouceAvgAggregateOutputType = {
  id: number | null
  planingId: number | null
  classId: number | null
}

export type RessouceSumAggregateOutputType = {
  id: number | null
  planingId: number | null
  classId: number | null
}

export type RessouceMinAggregateOutputType = {
  id: number | null
  name: string | null
  planingId: number | null
  classId: number | null
}

export type RessouceMaxAggregateOutputType = {
  id: number | null
  name: string | null
  planingId: number | null
  classId: number | null
}

export type RessouceCountAggregateOutputType = {
  id: number
  name: number
  planingId: number
  classId: number
  _all: number
}


export type RessouceAvgAggregateInputType = {
  id?: true
  planingId?: true
  classId?: true
}

export type RessouceSumAggregateInputType = {
  id?: true
  planingId?: true
  classId?: true
}

export type RessouceMinAggregateInputType = {
  id?: true
  name?: true
  planingId?: true
  classId?: true
}

export type RessouceMaxAggregateInputType = {
  id?: true
  name?: true
  planingId?: true
  classId?: true
}

export type RessouceCountAggregateInputType = {
  id?: true
  name?: true
  planingId?: true
  classId?: true
  _all?: true
}

export type RessouceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ressouce to aggregate.
   */
  where?: Prisma.RessouceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ressouces to fetch.
   */
  orderBy?: Prisma.RessouceOrderByWithRelationInput | Prisma.RessouceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RessouceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ressouces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ressouces.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Ressouces
  **/
  _count?: true | RessouceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RessouceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RessouceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RessouceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RessouceMaxAggregateInputType
}

export type GetRessouceAggregateType<T extends RessouceAggregateArgs> = {
      [P in keyof T & keyof AggregateRessouce]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRessouce[P]>
    : Prisma.GetScalarType<T[P], AggregateRessouce[P]>
}




export type RessouceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RessouceWhereInput
  orderBy?: Prisma.RessouceOrderByWithAggregationInput | Prisma.RessouceOrderByWithAggregationInput[]
  by: Prisma.RessouceScalarFieldEnum[] | Prisma.RessouceScalarFieldEnum
  having?: Prisma.RessouceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RessouceCountAggregateInputType | true
  _avg?: RessouceAvgAggregateInputType
  _sum?: RessouceSumAggregateInputType
  _min?: RessouceMinAggregateInputType
  _max?: RessouceMaxAggregateInputType
}

export type RessouceGroupByOutputType = {
  id: number
  name: string | null
  planingId: number | null
  classId: number | null
  _count: RessouceCountAggregateOutputType | null
  _avg: RessouceAvgAggregateOutputType | null
  _sum: RessouceSumAggregateOutputType | null
  _min: RessouceMinAggregateOutputType | null
  _max: RessouceMaxAggregateOutputType | null
}

type GetRessouceGroupByPayload<T extends RessouceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RessouceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RessouceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RessouceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RessouceGroupByOutputType[P]>
      }
    >
  >



export type RessouceWhereInput = {
  AND?: Prisma.RessouceWhereInput | Prisma.RessouceWhereInput[]
  OR?: Prisma.RessouceWhereInput[]
  NOT?: Prisma.RessouceWhereInput | Prisma.RessouceWhereInput[]
  id?: Prisma.IntFilter<"Ressouce"> | number
  name?: Prisma.StringNullableFilter<"Ressouce"> | string | null
  planingId?: Prisma.IntNullableFilter<"Ressouce"> | number | null
  classId?: Prisma.IntNullableFilter<"Ressouce"> | number | null
  class?: Prisma.XOR<Prisma.ClassNullableScalarRelationFilter, Prisma.ClassWhereInput> | null
  planing?: Prisma.XOR<Prisma.PlaningNullableScalarRelationFilter, Prisma.PlaningWhereInput> | null
}

export type RessouceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  planingId?: Prisma.SortOrderInput | Prisma.SortOrder
  classId?: Prisma.SortOrderInput | Prisma.SortOrder
  class?: Prisma.ClassOrderByWithRelationInput
  planing?: Prisma.PlaningOrderByWithRelationInput
}

export type RessouceWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.RessouceWhereInput | Prisma.RessouceWhereInput[]
  OR?: Prisma.RessouceWhereInput[]
  NOT?: Prisma.RessouceWhereInput | Prisma.RessouceWhereInput[]
  name?: Prisma.StringNullableFilter<"Ressouce"> | string | null
  planingId?: Prisma.IntNullableFilter<"Ressouce"> | number | null
  classId?: Prisma.IntNullableFilter<"Ressouce"> | number | null
  class?: Prisma.XOR<Prisma.ClassNullableScalarRelationFilter, Prisma.ClassWhereInput> | null
  planing?: Prisma.XOR<Prisma.PlaningNullableScalarRelationFilter, Prisma.PlaningWhereInput> | null
}, "id">

export type RessouceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  planingId?: Prisma.SortOrderInput | Prisma.SortOrder
  classId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RessouceCountOrderByAggregateInput
  _avg?: Prisma.RessouceAvgOrderByAggregateInput
  _max?: Prisma.RessouceMaxOrderByAggregateInput
  _min?: Prisma.RessouceMinOrderByAggregateInput
  _sum?: Prisma.RessouceSumOrderByAggregateInput
}

export type RessouceScalarWhereWithAggregatesInput = {
  AND?: Prisma.RessouceScalarWhereWithAggregatesInput | Prisma.RessouceScalarWhereWithAggregatesInput[]
  OR?: Prisma.RessouceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RessouceScalarWhereWithAggregatesInput | Prisma.RessouceScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Ressouce"> | number
  name?: Prisma.StringNullableWithAggregatesFilter<"Ressouce"> | string | null
  planingId?: Prisma.IntNullableWithAggregatesFilter<"Ressouce"> | number | null
  classId?: Prisma.IntNullableWithAggregatesFilter<"Ressouce"> | number | null
}

export type RessouceCreateInput = {
  name?: string | null
  class?: Prisma.ClassCreateNestedOneWithoutRessoucesInput
  planing?: Prisma.PlaningCreateNestedOneWithoutRessoucesInput
}

export type RessouceUncheckedCreateInput = {
  id?: number
  name?: string | null
  planingId?: number | null
  classId?: number | null
}

export type RessouceUpdateInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.ClassUpdateOneWithoutRessoucesNestedInput
  planing?: Prisma.PlaningUpdateOneWithoutRessoucesNestedInput
}

export type RessouceUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planingId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RessouceCreateManyInput = {
  id?: number
  name?: string | null
  planingId?: number | null
  classId?: number | null
}

export type RessouceUpdateManyMutationInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RessouceUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planingId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RessouceListRelationFilter = {
  every?: Prisma.RessouceWhereInput
  some?: Prisma.RessouceWhereInput
  none?: Prisma.RessouceWhereInput
}

export type RessouceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RessouceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  planingId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type RessouceAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planingId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type RessouceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  planingId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type RessouceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  planingId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type RessouceSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  planingId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type RessouceCreateNestedManyWithoutClassInput = {
  create?: Prisma.XOR<Prisma.RessouceCreateWithoutClassInput, Prisma.RessouceUncheckedCreateWithoutClassInput> | Prisma.RessouceCreateWithoutClassInput[] | Prisma.RessouceUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.RessouceCreateOrConnectWithoutClassInput | Prisma.RessouceCreateOrConnectWithoutClassInput[]
  createMany?: Prisma.RessouceCreateManyClassInputEnvelope
  connect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
}

export type RessouceUncheckedCreateNestedManyWithoutClassInput = {
  create?: Prisma.XOR<Prisma.RessouceCreateWithoutClassInput, Prisma.RessouceUncheckedCreateWithoutClassInput> | Prisma.RessouceCreateWithoutClassInput[] | Prisma.RessouceUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.RessouceCreateOrConnectWithoutClassInput | Prisma.RessouceCreateOrConnectWithoutClassInput[]
  createMany?: Prisma.RessouceCreateManyClassInputEnvelope
  connect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
}

export type RessouceUpdateManyWithoutClassNestedInput = {
  create?: Prisma.XOR<Prisma.RessouceCreateWithoutClassInput, Prisma.RessouceUncheckedCreateWithoutClassInput> | Prisma.RessouceCreateWithoutClassInput[] | Prisma.RessouceUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.RessouceCreateOrConnectWithoutClassInput | Prisma.RessouceCreateOrConnectWithoutClassInput[]
  upsert?: Prisma.RessouceUpsertWithWhereUniqueWithoutClassInput | Prisma.RessouceUpsertWithWhereUniqueWithoutClassInput[]
  createMany?: Prisma.RessouceCreateManyClassInputEnvelope
  set?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  disconnect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  delete?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  connect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  update?: Prisma.RessouceUpdateWithWhereUniqueWithoutClassInput | Prisma.RessouceUpdateWithWhereUniqueWithoutClassInput[]
  updateMany?: Prisma.RessouceUpdateManyWithWhereWithoutClassInput | Prisma.RessouceUpdateManyWithWhereWithoutClassInput[]
  deleteMany?: Prisma.RessouceScalarWhereInput | Prisma.RessouceScalarWhereInput[]
}

export type RessouceUncheckedUpdateManyWithoutClassNestedInput = {
  create?: Prisma.XOR<Prisma.RessouceCreateWithoutClassInput, Prisma.RessouceUncheckedCreateWithoutClassInput> | Prisma.RessouceCreateWithoutClassInput[] | Prisma.RessouceUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.RessouceCreateOrConnectWithoutClassInput | Prisma.RessouceCreateOrConnectWithoutClassInput[]
  upsert?: Prisma.RessouceUpsertWithWhereUniqueWithoutClassInput | Prisma.RessouceUpsertWithWhereUniqueWithoutClassInput[]
  createMany?: Prisma.RessouceCreateManyClassInputEnvelope
  set?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  disconnect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  delete?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  connect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  update?: Prisma.RessouceUpdateWithWhereUniqueWithoutClassInput | Prisma.RessouceUpdateWithWhereUniqueWithoutClassInput[]
  updateMany?: Prisma.RessouceUpdateManyWithWhereWithoutClassInput | Prisma.RessouceUpdateManyWithWhereWithoutClassInput[]
  deleteMany?: Prisma.RessouceScalarWhereInput | Prisma.RessouceScalarWhereInput[]
}

export type RessouceCreateNestedManyWithoutPlaningInput = {
  create?: Prisma.XOR<Prisma.RessouceCreateWithoutPlaningInput, Prisma.RessouceUncheckedCreateWithoutPlaningInput> | Prisma.RessouceCreateWithoutPlaningInput[] | Prisma.RessouceUncheckedCreateWithoutPlaningInput[]
  connectOrCreate?: Prisma.RessouceCreateOrConnectWithoutPlaningInput | Prisma.RessouceCreateOrConnectWithoutPlaningInput[]
  createMany?: Prisma.RessouceCreateManyPlaningInputEnvelope
  connect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
}

export type RessouceUncheckedCreateNestedManyWithoutPlaningInput = {
  create?: Prisma.XOR<Prisma.RessouceCreateWithoutPlaningInput, Prisma.RessouceUncheckedCreateWithoutPlaningInput> | Prisma.RessouceCreateWithoutPlaningInput[] | Prisma.RessouceUncheckedCreateWithoutPlaningInput[]
  connectOrCreate?: Prisma.RessouceCreateOrConnectWithoutPlaningInput | Prisma.RessouceCreateOrConnectWithoutPlaningInput[]
  createMany?: Prisma.RessouceCreateManyPlaningInputEnvelope
  connect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
}

export type RessouceUpdateManyWithoutPlaningNestedInput = {
  create?: Prisma.XOR<Prisma.RessouceCreateWithoutPlaningInput, Prisma.RessouceUncheckedCreateWithoutPlaningInput> | Prisma.RessouceCreateWithoutPlaningInput[] | Prisma.RessouceUncheckedCreateWithoutPlaningInput[]
  connectOrCreate?: Prisma.RessouceCreateOrConnectWithoutPlaningInput | Prisma.RessouceCreateOrConnectWithoutPlaningInput[]
  upsert?: Prisma.RessouceUpsertWithWhereUniqueWithoutPlaningInput | Prisma.RessouceUpsertWithWhereUniqueWithoutPlaningInput[]
  createMany?: Prisma.RessouceCreateManyPlaningInputEnvelope
  set?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  disconnect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  delete?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  connect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  update?: Prisma.RessouceUpdateWithWhereUniqueWithoutPlaningInput | Prisma.RessouceUpdateWithWhereUniqueWithoutPlaningInput[]
  updateMany?: Prisma.RessouceUpdateManyWithWhereWithoutPlaningInput | Prisma.RessouceUpdateManyWithWhereWithoutPlaningInput[]
  deleteMany?: Prisma.RessouceScalarWhereInput | Prisma.RessouceScalarWhereInput[]
}

export type RessouceUncheckedUpdateManyWithoutPlaningNestedInput = {
  create?: Prisma.XOR<Prisma.RessouceCreateWithoutPlaningInput, Prisma.RessouceUncheckedCreateWithoutPlaningInput> | Prisma.RessouceCreateWithoutPlaningInput[] | Prisma.RessouceUncheckedCreateWithoutPlaningInput[]
  connectOrCreate?: Prisma.RessouceCreateOrConnectWithoutPlaningInput | Prisma.RessouceCreateOrConnectWithoutPlaningInput[]
  upsert?: Prisma.RessouceUpsertWithWhereUniqueWithoutPlaningInput | Prisma.RessouceUpsertWithWhereUniqueWithoutPlaningInput[]
  createMany?: Prisma.RessouceCreateManyPlaningInputEnvelope
  set?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  disconnect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  delete?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  connect?: Prisma.RessouceWhereUniqueInput | Prisma.RessouceWhereUniqueInput[]
  update?: Prisma.RessouceUpdateWithWhereUniqueWithoutPlaningInput | Prisma.RessouceUpdateWithWhereUniqueWithoutPlaningInput[]
  updateMany?: Prisma.RessouceUpdateManyWithWhereWithoutPlaningInput | Prisma.RessouceUpdateManyWithWhereWithoutPlaningInput[]
  deleteMany?: Prisma.RessouceScalarWhereInput | Prisma.RessouceScalarWhereInput[]
}

export type RessouceCreateWithoutClassInput = {
  name?: string | null
  planing?: Prisma.PlaningCreateNestedOneWithoutRessoucesInput
}

export type RessouceUncheckedCreateWithoutClassInput = {
  id?: number
  name?: string | null
  planingId?: number | null
}

export type RessouceCreateOrConnectWithoutClassInput = {
  where: Prisma.RessouceWhereUniqueInput
  create: Prisma.XOR<Prisma.RessouceCreateWithoutClassInput, Prisma.RessouceUncheckedCreateWithoutClassInput>
}

export type RessouceCreateManyClassInputEnvelope = {
  data: Prisma.RessouceCreateManyClassInput | Prisma.RessouceCreateManyClassInput[]
  skipDuplicates?: boolean
}

export type RessouceUpsertWithWhereUniqueWithoutClassInput = {
  where: Prisma.RessouceWhereUniqueInput
  update: Prisma.XOR<Prisma.RessouceUpdateWithoutClassInput, Prisma.RessouceUncheckedUpdateWithoutClassInput>
  create: Prisma.XOR<Prisma.RessouceCreateWithoutClassInput, Prisma.RessouceUncheckedCreateWithoutClassInput>
}

export type RessouceUpdateWithWhereUniqueWithoutClassInput = {
  where: Prisma.RessouceWhereUniqueInput
  data: Prisma.XOR<Prisma.RessouceUpdateWithoutClassInput, Prisma.RessouceUncheckedUpdateWithoutClassInput>
}

export type RessouceUpdateManyWithWhereWithoutClassInput = {
  where: Prisma.RessouceScalarWhereInput
  data: Prisma.XOR<Prisma.RessouceUpdateManyMutationInput, Prisma.RessouceUncheckedUpdateManyWithoutClassInput>
}

export type RessouceScalarWhereInput = {
  AND?: Prisma.RessouceScalarWhereInput | Prisma.RessouceScalarWhereInput[]
  OR?: Prisma.RessouceScalarWhereInput[]
  NOT?: Prisma.RessouceScalarWhereInput | Prisma.RessouceScalarWhereInput[]
  id?: Prisma.IntFilter<"Ressouce"> | number
  name?: Prisma.StringNullableFilter<"Ressouce"> | string | null
  planingId?: Prisma.IntNullableFilter<"Ressouce"> | number | null
  classId?: Prisma.IntNullableFilter<"Ressouce"> | number | null
}

export type RessouceCreateWithoutPlaningInput = {
  name?: string | null
  class?: Prisma.ClassCreateNestedOneWithoutRessoucesInput
}

export type RessouceUncheckedCreateWithoutPlaningInput = {
  id?: number
  name?: string | null
  classId?: number | null
}

export type RessouceCreateOrConnectWithoutPlaningInput = {
  where: Prisma.RessouceWhereUniqueInput
  create: Prisma.XOR<Prisma.RessouceCreateWithoutPlaningInput, Prisma.RessouceUncheckedCreateWithoutPlaningInput>
}

export type RessouceCreateManyPlaningInputEnvelope = {
  data: Prisma.RessouceCreateManyPlaningInput | Prisma.RessouceCreateManyPlaningInput[]
  skipDuplicates?: boolean
}

export type RessouceUpsertWithWhereUniqueWithoutPlaningInput = {
  where: Prisma.RessouceWhereUniqueInput
  update: Prisma.XOR<Prisma.RessouceUpdateWithoutPlaningInput, Prisma.RessouceUncheckedUpdateWithoutPlaningInput>
  create: Prisma.XOR<Prisma.RessouceCreateWithoutPlaningInput, Prisma.RessouceUncheckedCreateWithoutPlaningInput>
}

export type RessouceUpdateWithWhereUniqueWithoutPlaningInput = {
  where: Prisma.RessouceWhereUniqueInput
  data: Prisma.XOR<Prisma.RessouceUpdateWithoutPlaningInput, Prisma.RessouceUncheckedUpdateWithoutPlaningInput>
}

export type RessouceUpdateManyWithWhereWithoutPlaningInput = {
  where: Prisma.RessouceScalarWhereInput
  data: Prisma.XOR<Prisma.RessouceUpdateManyMutationInput, Prisma.RessouceUncheckedUpdateManyWithoutPlaningInput>
}

export type RessouceCreateManyClassInput = {
  id?: number
  name?: string | null
  planingId?: number | null
}

export type RessouceUpdateWithoutClassInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planing?: Prisma.PlaningUpdateOneWithoutRessoucesNestedInput
}

export type RessouceUncheckedUpdateWithoutClassInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planingId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RessouceUncheckedUpdateManyWithoutClassInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planingId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RessouceCreateManyPlaningInput = {
  id?: number
  name?: string | null
  classId?: number | null
}

export type RessouceUpdateWithoutPlaningInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.ClassUpdateOneWithoutRessoucesNestedInput
}

export type RessouceUncheckedUpdateWithoutPlaningInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RessouceUncheckedUpdateManyWithoutPlaningInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type RessouceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  planingId?: boolean
  classId?: boolean
  class?: boolean | Prisma.Ressouce$classArgs<ExtArgs>
  planing?: boolean | Prisma.Ressouce$planingArgs<ExtArgs>
}, ExtArgs["result"]["ressouce"]>

export type RessouceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  planingId?: boolean
  classId?: boolean
  class?: boolean | Prisma.Ressouce$classArgs<ExtArgs>
  planing?: boolean | Prisma.Ressouce$planingArgs<ExtArgs>
}, ExtArgs["result"]["ressouce"]>

export type RessouceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  planingId?: boolean
  classId?: boolean
  class?: boolean | Prisma.Ressouce$classArgs<ExtArgs>
  planing?: boolean | Prisma.Ressouce$planingArgs<ExtArgs>
}, ExtArgs["result"]["ressouce"]>

export type RessouceSelectScalar = {
  id?: boolean
  name?: boolean
  planingId?: boolean
  classId?: boolean
}

export type RessouceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "planingId" | "classId", ExtArgs["result"]["ressouce"]>
export type RessouceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.Ressouce$classArgs<ExtArgs>
  planing?: boolean | Prisma.Ressouce$planingArgs<ExtArgs>
}
export type RessouceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.Ressouce$classArgs<ExtArgs>
  planing?: boolean | Prisma.Ressouce$planingArgs<ExtArgs>
}
export type RessouceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.Ressouce$classArgs<ExtArgs>
  planing?: boolean | Prisma.Ressouce$planingArgs<ExtArgs>
}

export type $RessoucePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Ressouce"
  objects: {
    class: Prisma.$ClassPayload<ExtArgs> | null
    planing: Prisma.$PlaningPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string | null
    planingId: number | null
    classId: number | null
  }, ExtArgs["result"]["ressouce"]>
  composites: {}
}

export type RessouceGetPayload<S extends boolean | null | undefined | RessouceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RessoucePayload, S>

export type RessouceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RessouceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RessouceCountAggregateInputType | true
  }

export interface RessouceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Ressouce'], meta: { name: 'Ressouce' } }
  /**
   * Find zero or one Ressouce that matches the filter.
   * @param {RessouceFindUniqueArgs} args - Arguments to find a Ressouce
   * @example
   * // Get one Ressouce
   * const ressouce = await prisma.ressouce.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RessouceFindUniqueArgs>(args: Prisma.SelectSubset<T, RessouceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RessouceClient<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Ressouce that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RessouceFindUniqueOrThrowArgs} args - Arguments to find a Ressouce
   * @example
   * // Get one Ressouce
   * const ressouce = await prisma.ressouce.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RessouceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RessouceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RessouceClient<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ressouce that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RessouceFindFirstArgs} args - Arguments to find a Ressouce
   * @example
   * // Get one Ressouce
   * const ressouce = await prisma.ressouce.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RessouceFindFirstArgs>(args?: Prisma.SelectSubset<T, RessouceFindFirstArgs<ExtArgs>>): Prisma.Prisma__RessouceClient<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ressouce that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RessouceFindFirstOrThrowArgs} args - Arguments to find a Ressouce
   * @example
   * // Get one Ressouce
   * const ressouce = await prisma.ressouce.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RessouceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RessouceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RessouceClient<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Ressouces that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RessouceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Ressouces
   * const ressouces = await prisma.ressouce.findMany()
   * 
   * // Get first 10 Ressouces
   * const ressouces = await prisma.ressouce.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ressouceWithIdOnly = await prisma.ressouce.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RessouceFindManyArgs>(args?: Prisma.SelectSubset<T, RessouceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Ressouce.
   * @param {RessouceCreateArgs} args - Arguments to create a Ressouce.
   * @example
   * // Create one Ressouce
   * const Ressouce = await prisma.ressouce.create({
   *   data: {
   *     // ... data to create a Ressouce
   *   }
   * })
   * 
   */
  create<T extends RessouceCreateArgs>(args: Prisma.SelectSubset<T, RessouceCreateArgs<ExtArgs>>): Prisma.Prisma__RessouceClient<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Ressouces.
   * @param {RessouceCreateManyArgs} args - Arguments to create many Ressouces.
   * @example
   * // Create many Ressouces
   * const ressouce = await prisma.ressouce.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RessouceCreateManyArgs>(args?: Prisma.SelectSubset<T, RessouceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Ressouces and returns the data saved in the database.
   * @param {RessouceCreateManyAndReturnArgs} args - Arguments to create many Ressouces.
   * @example
   * // Create many Ressouces
   * const ressouce = await prisma.ressouce.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Ressouces and only return the `id`
   * const ressouceWithIdOnly = await prisma.ressouce.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RessouceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RessouceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Ressouce.
   * @param {RessouceDeleteArgs} args - Arguments to delete one Ressouce.
   * @example
   * // Delete one Ressouce
   * const Ressouce = await prisma.ressouce.delete({
   *   where: {
   *     // ... filter to delete one Ressouce
   *   }
   * })
   * 
   */
  delete<T extends RessouceDeleteArgs>(args: Prisma.SelectSubset<T, RessouceDeleteArgs<ExtArgs>>): Prisma.Prisma__RessouceClient<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Ressouce.
   * @param {RessouceUpdateArgs} args - Arguments to update one Ressouce.
   * @example
   * // Update one Ressouce
   * const ressouce = await prisma.ressouce.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RessouceUpdateArgs>(args: Prisma.SelectSubset<T, RessouceUpdateArgs<ExtArgs>>): Prisma.Prisma__RessouceClient<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Ressouces.
   * @param {RessouceDeleteManyArgs} args - Arguments to filter Ressouces to delete.
   * @example
   * // Delete a few Ressouces
   * const { count } = await prisma.ressouce.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RessouceDeleteManyArgs>(args?: Prisma.SelectSubset<T, RessouceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Ressouces.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RessouceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Ressouces
   * const ressouce = await prisma.ressouce.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RessouceUpdateManyArgs>(args: Prisma.SelectSubset<T, RessouceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Ressouces and returns the data updated in the database.
   * @param {RessouceUpdateManyAndReturnArgs} args - Arguments to update many Ressouces.
   * @example
   * // Update many Ressouces
   * const ressouce = await prisma.ressouce.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Ressouces and only return the `id`
   * const ressouceWithIdOnly = await prisma.ressouce.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RessouceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RessouceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Ressouce.
   * @param {RessouceUpsertArgs} args - Arguments to update or create a Ressouce.
   * @example
   * // Update or create a Ressouce
   * const ressouce = await prisma.ressouce.upsert({
   *   create: {
   *     // ... data to create a Ressouce
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Ressouce we want to update
   *   }
   * })
   */
  upsert<T extends RessouceUpsertArgs>(args: Prisma.SelectSubset<T, RessouceUpsertArgs<ExtArgs>>): Prisma.Prisma__RessouceClient<runtime.Types.Result.GetResult<Prisma.$RessoucePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Ressouces.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RessouceCountArgs} args - Arguments to filter Ressouces to count.
   * @example
   * // Count the number of Ressouces
   * const count = await prisma.ressouce.count({
   *   where: {
   *     // ... the filter for the Ressouces we want to count
   *   }
   * })
  **/
  count<T extends RessouceCountArgs>(
    args?: Prisma.Subset<T, RessouceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RessouceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Ressouce.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RessouceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RessouceAggregateArgs>(args: Prisma.Subset<T, RessouceAggregateArgs>): Prisma.PrismaPromise<GetRessouceAggregateType<T>>

  /**
   * Group by Ressouce.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RessouceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RessouceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RessouceGroupByArgs['orderBy'] }
      : { orderBy?: RessouceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RessouceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRessouceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Ressouce model
 */
readonly fields: RessouceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Ressouce.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RessouceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  class<T extends Prisma.Ressouce$classArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Ressouce$classArgs<ExtArgs>>): Prisma.Prisma__ClassClient<runtime.Types.Result.GetResult<Prisma.$ClassPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  planing<T extends Prisma.Ressouce$planingArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Ressouce$planingArgs<ExtArgs>>): Prisma.Prisma__PlaningClient<runtime.Types.Result.GetResult<Prisma.$PlaningPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Ressouce model
 */
export interface RessouceFieldRefs {
  readonly id: Prisma.FieldRef<"Ressouce", 'Int'>
  readonly name: Prisma.FieldRef<"Ressouce", 'String'>
  readonly planingId: Prisma.FieldRef<"Ressouce", 'Int'>
  readonly classId: Prisma.FieldRef<"Ressouce", 'Int'>
}
    

// Custom InputTypes
/**
 * Ressouce findUnique
 */
export type RessouceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
  /**
   * Filter, which Ressouce to fetch.
   */
  where: Prisma.RessouceWhereUniqueInput
}

/**
 * Ressouce findUniqueOrThrow
 */
export type RessouceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
  /**
   * Filter, which Ressouce to fetch.
   */
  where: Prisma.RessouceWhereUniqueInput
}

/**
 * Ressouce findFirst
 */
export type RessouceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
  /**
   * Filter, which Ressouce to fetch.
   */
  where?: Prisma.RessouceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ressouces to fetch.
   */
  orderBy?: Prisma.RessouceOrderByWithRelationInput | Prisma.RessouceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Ressouces.
   */
  cursor?: Prisma.RessouceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ressouces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ressouces.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Ressouces.
   */
  distinct?: Prisma.RessouceScalarFieldEnum | Prisma.RessouceScalarFieldEnum[]
}

/**
 * Ressouce findFirstOrThrow
 */
export type RessouceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
  /**
   * Filter, which Ressouce to fetch.
   */
  where?: Prisma.RessouceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ressouces to fetch.
   */
  orderBy?: Prisma.RessouceOrderByWithRelationInput | Prisma.RessouceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Ressouces.
   */
  cursor?: Prisma.RessouceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ressouces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ressouces.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Ressouces.
   */
  distinct?: Prisma.RessouceScalarFieldEnum | Prisma.RessouceScalarFieldEnum[]
}

/**
 * Ressouce findMany
 */
export type RessouceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
  /**
   * Filter, which Ressouces to fetch.
   */
  where?: Prisma.RessouceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Ressouces to fetch.
   */
  orderBy?: Prisma.RessouceOrderByWithRelationInput | Prisma.RessouceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Ressouces.
   */
  cursor?: Prisma.RessouceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Ressouces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Ressouces.
   */
  skip?: number
  distinct?: Prisma.RessouceScalarFieldEnum | Prisma.RessouceScalarFieldEnum[]
}

/**
 * Ressouce create
 */
export type RessouceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
  /**
   * The data needed to create a Ressouce.
   */
  data?: Prisma.XOR<Prisma.RessouceCreateInput, Prisma.RessouceUncheckedCreateInput>
}

/**
 * Ressouce createMany
 */
export type RessouceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Ressouces.
   */
  data: Prisma.RessouceCreateManyInput | Prisma.RessouceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Ressouce createManyAndReturn
 */
export type RessouceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * The data used to create many Ressouces.
   */
  data: Prisma.RessouceCreateManyInput | Prisma.RessouceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Ressouce update
 */
export type RessouceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
  /**
   * The data needed to update a Ressouce.
   */
  data: Prisma.XOR<Prisma.RessouceUpdateInput, Prisma.RessouceUncheckedUpdateInput>
  /**
   * Choose, which Ressouce to update.
   */
  where: Prisma.RessouceWhereUniqueInput
}

/**
 * Ressouce updateMany
 */
export type RessouceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Ressouces.
   */
  data: Prisma.XOR<Prisma.RessouceUpdateManyMutationInput, Prisma.RessouceUncheckedUpdateManyInput>
  /**
   * Filter which Ressouces to update
   */
  where?: Prisma.RessouceWhereInput
  /**
   * Limit how many Ressouces to update.
   */
  limit?: number
}

/**
 * Ressouce updateManyAndReturn
 */
export type RessouceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * The data used to update Ressouces.
   */
  data: Prisma.XOR<Prisma.RessouceUpdateManyMutationInput, Prisma.RessouceUncheckedUpdateManyInput>
  /**
   * Filter which Ressouces to update
   */
  where?: Prisma.RessouceWhereInput
  /**
   * Limit how many Ressouces to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Ressouce upsert
 */
export type RessouceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
  /**
   * The filter to search for the Ressouce to update in case it exists.
   */
  where: Prisma.RessouceWhereUniqueInput
  /**
   * In case the Ressouce found by the `where` argument doesn't exist, create a new Ressouce with this data.
   */
  create: Prisma.XOR<Prisma.RessouceCreateInput, Prisma.RessouceUncheckedCreateInput>
  /**
   * In case the Ressouce was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RessouceUpdateInput, Prisma.RessouceUncheckedUpdateInput>
}

/**
 * Ressouce delete
 */
export type RessouceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
  /**
   * Filter which Ressouce to delete.
   */
  where: Prisma.RessouceWhereUniqueInput
}

/**
 * Ressouce deleteMany
 */
export type RessouceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ressouces to delete
   */
  where?: Prisma.RessouceWhereInput
  /**
   * Limit how many Ressouces to delete.
   */
  limit?: number
}

/**
 * Ressouce.class
 */
export type Ressouce$classArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Class
   */
  select?: Prisma.ClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Class
   */
  omit?: Prisma.ClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClassInclude<ExtArgs> | null
  where?: Prisma.ClassWhereInput
}

/**
 * Ressouce.planing
 */
export type Ressouce$planingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Planing
   */
  select?: Prisma.PlaningSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Planing
   */
  omit?: Prisma.PlaningOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaningInclude<ExtArgs> | null
  where?: Prisma.PlaningWhereInput
}

/**
 * Ressouce without action
 */
export type RessouceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ressouce
   */
  select?: Prisma.RessouceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ressouce
   */
  omit?: Prisma.RessouceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RessouceInclude<ExtArgs> | null
}
