
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Taf` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Taf
 * 
 */
export type TafModel = runtime.Types.Result.DefaultSelection<Prisma.$TafPayload>

export type AggregateTaf = {
  _count: TafCountAggregateOutputType | null
  _avg: TafAvgAggregateOutputType | null
  _sum: TafSumAggregateOutputType | null
  _min: TafMinAggregateOutputType | null
  _max: TafMaxAggregateOutputType | null
}

export type TafAvgAggregateOutputType = {
  id: number | null
  subjectId: number | null
  classId: number | null
}

export type TafSumAggregateOutputType = {
  id: number | null
  subjectId: number | null
  classId: number | null
}

export type TafMinAggregateOutputType = {
  id: number | null
  subjectId: number | null
  classId: number | null
  type: string | null
  dateTaf: Date | null
  description: string | null
}

export type TafMaxAggregateOutputType = {
  id: number | null
  subjectId: number | null
  classId: number | null
  type: string | null
  dateTaf: Date | null
  description: string | null
}

export type TafCountAggregateOutputType = {
  id: number
  subjectId: number
  classId: number
  type: number
  dateTaf: number
  description: number
  _all: number
}


export type TafAvgAggregateInputType = {
  id?: true
  subjectId?: true
  classId?: true
}

export type TafSumAggregateInputType = {
  id?: true
  subjectId?: true
  classId?: true
}

export type TafMinAggregateInputType = {
  id?: true
  subjectId?: true
  classId?: true
  type?: true
  dateTaf?: true
  description?: true
}

export type TafMaxAggregateInputType = {
  id?: true
  subjectId?: true
  classId?: true
  type?: true
  dateTaf?: true
  description?: true
}

export type TafCountAggregateInputType = {
  id?: true
  subjectId?: true
  classId?: true
  type?: true
  dateTaf?: true
  description?: true
  _all?: true
}

export type TafAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Taf to aggregate.
   */
  where?: Prisma.TafWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tafs to fetch.
   */
  orderBy?: Prisma.TafOrderByWithRelationInput | Prisma.TafOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TafWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tafs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tafs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tafs
  **/
  _count?: true | TafCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TafAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TafSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TafMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TafMaxAggregateInputType
}

export type GetTafAggregateType<T extends TafAggregateArgs> = {
      [P in keyof T & keyof AggregateTaf]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTaf[P]>
    : Prisma.GetScalarType<T[P], AggregateTaf[P]>
}




export type TafGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TafWhereInput
  orderBy?: Prisma.TafOrderByWithAggregationInput | Prisma.TafOrderByWithAggregationInput[]
  by: Prisma.TafScalarFieldEnum[] | Prisma.TafScalarFieldEnum
  having?: Prisma.TafScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TafCountAggregateInputType | true
  _avg?: TafAvgAggregateInputType
  _sum?: TafSumAggregateInputType
  _min?: TafMinAggregateInputType
  _max?: TafMaxAggregateInputType
}

export type TafGroupByOutputType = {
  id: number
  subjectId: number | null
  classId: number | null
  type: string | null
  dateTaf: Date | null
  description: string | null
  _count: TafCountAggregateOutputType | null
  _avg: TafAvgAggregateOutputType | null
  _sum: TafSumAggregateOutputType | null
  _min: TafMinAggregateOutputType | null
  _max: TafMaxAggregateOutputType | null
}

type GetTafGroupByPayload<T extends TafGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TafGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TafGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TafGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TafGroupByOutputType[P]>
      }
    >
  >



export type TafWhereInput = {
  AND?: Prisma.TafWhereInput | Prisma.TafWhereInput[]
  OR?: Prisma.TafWhereInput[]
  NOT?: Prisma.TafWhereInput | Prisma.TafWhereInput[]
  id?: Prisma.IntFilter<"Taf"> | number
  subjectId?: Prisma.IntNullableFilter<"Taf"> | number | null
  classId?: Prisma.IntNullableFilter<"Taf"> | number | null
  type?: Prisma.StringNullableFilter<"Taf"> | string | null
  dateTaf?: Prisma.DateTimeNullableFilter<"Taf"> | Date | string | null
  description?: Prisma.StringNullableFilter<"Taf"> | string | null
  class?: Prisma.XOR<Prisma.ClassNullableScalarRelationFilter, Prisma.ClassWhereInput> | null
  subject?: Prisma.XOR<Prisma.SubjectNullableScalarRelationFilter, Prisma.SubjectWhereInput> | null
  files?: Prisma.FileListRelationFilter
}

export type TafOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  subjectId?: Prisma.SortOrderInput | Prisma.SortOrder
  classId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  dateTaf?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  class?: Prisma.ClassOrderByWithRelationInput
  subject?: Prisma.SubjectOrderByWithRelationInput
  files?: Prisma.fileOrderByRelationAggregateInput
}

export type TafWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.TafWhereInput | Prisma.TafWhereInput[]
  OR?: Prisma.TafWhereInput[]
  NOT?: Prisma.TafWhereInput | Prisma.TafWhereInput[]
  subjectId?: Prisma.IntNullableFilter<"Taf"> | number | null
  classId?: Prisma.IntNullableFilter<"Taf"> | number | null
  type?: Prisma.StringNullableFilter<"Taf"> | string | null
  dateTaf?: Prisma.DateTimeNullableFilter<"Taf"> | Date | string | null
  description?: Prisma.StringNullableFilter<"Taf"> | string | null
  class?: Prisma.XOR<Prisma.ClassNullableScalarRelationFilter, Prisma.ClassWhereInput> | null
  subject?: Prisma.XOR<Prisma.SubjectNullableScalarRelationFilter, Prisma.SubjectWhereInput> | null
  files?: Prisma.FileListRelationFilter
}, "id">

export type TafOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  subjectId?: Prisma.SortOrderInput | Prisma.SortOrder
  classId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  dateTaf?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TafCountOrderByAggregateInput
  _avg?: Prisma.TafAvgOrderByAggregateInput
  _max?: Prisma.TafMaxOrderByAggregateInput
  _min?: Prisma.TafMinOrderByAggregateInput
  _sum?: Prisma.TafSumOrderByAggregateInput
}

export type TafScalarWhereWithAggregatesInput = {
  AND?: Prisma.TafScalarWhereWithAggregatesInput | Prisma.TafScalarWhereWithAggregatesInput[]
  OR?: Prisma.TafScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TafScalarWhereWithAggregatesInput | Prisma.TafScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Taf"> | number
  subjectId?: Prisma.IntNullableWithAggregatesFilter<"Taf"> | number | null
  classId?: Prisma.IntNullableWithAggregatesFilter<"Taf"> | number | null
  type?: Prisma.StringNullableWithAggregatesFilter<"Taf"> | string | null
  dateTaf?: Prisma.DateTimeNullableWithAggregatesFilter<"Taf"> | Date | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Taf"> | string | null
}

export type TafCreateInput = {
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
  class?: Prisma.ClassCreateNestedOneWithoutTafsInput
  subject?: Prisma.SubjectCreateNestedOneWithoutTafsInput
  files?: Prisma.fileCreateNestedManyWithoutTafInput
}

export type TafUncheckedCreateInput = {
  id?: number
  subjectId?: number | null
  classId?: number | null
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
  files?: Prisma.fileUncheckedCreateNestedManyWithoutTafInput
}

export type TafUpdateInput = {
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.ClassUpdateOneWithoutTafsNestedInput
  subject?: Prisma.SubjectUpdateOneWithoutTafsNestedInput
  files?: Prisma.fileUpdateManyWithoutTafNestedInput
}

export type TafUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  subjectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.fileUncheckedUpdateManyWithoutTafNestedInput
}

export type TafCreateManyInput = {
  id?: number
  subjectId?: number | null
  classId?: number | null
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
}

export type TafUpdateManyMutationInput = {
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TafUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  subjectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TafListRelationFilter = {
  every?: Prisma.TafWhereInput
  some?: Prisma.TafWhereInput
  none?: Prisma.TafWhereInput
}

export type TafOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TafCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  dateTaf?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type TafAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type TafMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  dateTaf?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type TafMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  dateTaf?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type TafSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  classId?: Prisma.SortOrder
}

export type TafNullableScalarRelationFilter = {
  is?: Prisma.TafWhereInput | null
  isNot?: Prisma.TafWhereInput | null
}

export type TafCreateNestedManyWithoutClassInput = {
  create?: Prisma.XOR<Prisma.TafCreateWithoutClassInput, Prisma.TafUncheckedCreateWithoutClassInput> | Prisma.TafCreateWithoutClassInput[] | Prisma.TafUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.TafCreateOrConnectWithoutClassInput | Prisma.TafCreateOrConnectWithoutClassInput[]
  createMany?: Prisma.TafCreateManyClassInputEnvelope
  connect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
}

export type TafUncheckedCreateNestedManyWithoutClassInput = {
  create?: Prisma.XOR<Prisma.TafCreateWithoutClassInput, Prisma.TafUncheckedCreateWithoutClassInput> | Prisma.TafCreateWithoutClassInput[] | Prisma.TafUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.TafCreateOrConnectWithoutClassInput | Prisma.TafCreateOrConnectWithoutClassInput[]
  createMany?: Prisma.TafCreateManyClassInputEnvelope
  connect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
}

export type TafUpdateManyWithoutClassNestedInput = {
  create?: Prisma.XOR<Prisma.TafCreateWithoutClassInput, Prisma.TafUncheckedCreateWithoutClassInput> | Prisma.TafCreateWithoutClassInput[] | Prisma.TafUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.TafCreateOrConnectWithoutClassInput | Prisma.TafCreateOrConnectWithoutClassInput[]
  upsert?: Prisma.TafUpsertWithWhereUniqueWithoutClassInput | Prisma.TafUpsertWithWhereUniqueWithoutClassInput[]
  createMany?: Prisma.TafCreateManyClassInputEnvelope
  set?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  disconnect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  delete?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  connect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  update?: Prisma.TafUpdateWithWhereUniqueWithoutClassInput | Prisma.TafUpdateWithWhereUniqueWithoutClassInput[]
  updateMany?: Prisma.TafUpdateManyWithWhereWithoutClassInput | Prisma.TafUpdateManyWithWhereWithoutClassInput[]
  deleteMany?: Prisma.TafScalarWhereInput | Prisma.TafScalarWhereInput[]
}

export type TafUncheckedUpdateManyWithoutClassNestedInput = {
  create?: Prisma.XOR<Prisma.TafCreateWithoutClassInput, Prisma.TafUncheckedCreateWithoutClassInput> | Prisma.TafCreateWithoutClassInput[] | Prisma.TafUncheckedCreateWithoutClassInput[]
  connectOrCreate?: Prisma.TafCreateOrConnectWithoutClassInput | Prisma.TafCreateOrConnectWithoutClassInput[]
  upsert?: Prisma.TafUpsertWithWhereUniqueWithoutClassInput | Prisma.TafUpsertWithWhereUniqueWithoutClassInput[]
  createMany?: Prisma.TafCreateManyClassInputEnvelope
  set?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  disconnect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  delete?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  connect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  update?: Prisma.TafUpdateWithWhereUniqueWithoutClassInput | Prisma.TafUpdateWithWhereUniqueWithoutClassInput[]
  updateMany?: Prisma.TafUpdateManyWithWhereWithoutClassInput | Prisma.TafUpdateManyWithWhereWithoutClassInput[]
  deleteMany?: Prisma.TafScalarWhereInput | Prisma.TafScalarWhereInput[]
}

export type TafCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.TafCreateWithoutSubjectInput, Prisma.TafUncheckedCreateWithoutSubjectInput> | Prisma.TafCreateWithoutSubjectInput[] | Prisma.TafUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.TafCreateOrConnectWithoutSubjectInput | Prisma.TafCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.TafCreateManySubjectInputEnvelope
  connect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
}

export type TafUncheckedCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.TafCreateWithoutSubjectInput, Prisma.TafUncheckedCreateWithoutSubjectInput> | Prisma.TafCreateWithoutSubjectInput[] | Prisma.TafUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.TafCreateOrConnectWithoutSubjectInput | Prisma.TafCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.TafCreateManySubjectInputEnvelope
  connect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
}

export type TafUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.TafCreateWithoutSubjectInput, Prisma.TafUncheckedCreateWithoutSubjectInput> | Prisma.TafCreateWithoutSubjectInput[] | Prisma.TafUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.TafCreateOrConnectWithoutSubjectInput | Prisma.TafCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.TafUpsertWithWhereUniqueWithoutSubjectInput | Prisma.TafUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.TafCreateManySubjectInputEnvelope
  set?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  disconnect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  delete?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  connect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  update?: Prisma.TafUpdateWithWhereUniqueWithoutSubjectInput | Prisma.TafUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.TafUpdateManyWithWhereWithoutSubjectInput | Prisma.TafUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.TafScalarWhereInput | Prisma.TafScalarWhereInput[]
}

export type TafUncheckedUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.TafCreateWithoutSubjectInput, Prisma.TafUncheckedCreateWithoutSubjectInput> | Prisma.TafCreateWithoutSubjectInput[] | Prisma.TafUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.TafCreateOrConnectWithoutSubjectInput | Prisma.TafCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.TafUpsertWithWhereUniqueWithoutSubjectInput | Prisma.TafUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.TafCreateManySubjectInputEnvelope
  set?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  disconnect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  delete?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  connect?: Prisma.TafWhereUniqueInput | Prisma.TafWhereUniqueInput[]
  update?: Prisma.TafUpdateWithWhereUniqueWithoutSubjectInput | Prisma.TafUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.TafUpdateManyWithWhereWithoutSubjectInput | Prisma.TafUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.TafScalarWhereInput | Prisma.TafScalarWhereInput[]
}

export type TafCreateNestedOneWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.TafCreateWithoutFilesInput, Prisma.TafUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.TafCreateOrConnectWithoutFilesInput
  connect?: Prisma.TafWhereUniqueInput
}

export type TafUpdateOneWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.TafCreateWithoutFilesInput, Prisma.TafUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.TafCreateOrConnectWithoutFilesInput
  upsert?: Prisma.TafUpsertWithoutFilesInput
  disconnect?: Prisma.TafWhereInput | boolean
  delete?: Prisma.TafWhereInput | boolean
  connect?: Prisma.TafWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TafUpdateToOneWithWhereWithoutFilesInput, Prisma.TafUpdateWithoutFilesInput>, Prisma.TafUncheckedUpdateWithoutFilesInput>
}

export type TafCreateWithoutClassInput = {
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
  subject?: Prisma.SubjectCreateNestedOneWithoutTafsInput
  files?: Prisma.fileCreateNestedManyWithoutTafInput
}

export type TafUncheckedCreateWithoutClassInput = {
  id?: number
  subjectId?: number | null
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
  files?: Prisma.fileUncheckedCreateNestedManyWithoutTafInput
}

export type TafCreateOrConnectWithoutClassInput = {
  where: Prisma.TafWhereUniqueInput
  create: Prisma.XOR<Prisma.TafCreateWithoutClassInput, Prisma.TafUncheckedCreateWithoutClassInput>
}

export type TafCreateManyClassInputEnvelope = {
  data: Prisma.TafCreateManyClassInput | Prisma.TafCreateManyClassInput[]
  skipDuplicates?: boolean
}

export type TafUpsertWithWhereUniqueWithoutClassInput = {
  where: Prisma.TafWhereUniqueInput
  update: Prisma.XOR<Prisma.TafUpdateWithoutClassInput, Prisma.TafUncheckedUpdateWithoutClassInput>
  create: Prisma.XOR<Prisma.TafCreateWithoutClassInput, Prisma.TafUncheckedCreateWithoutClassInput>
}

export type TafUpdateWithWhereUniqueWithoutClassInput = {
  where: Prisma.TafWhereUniqueInput
  data: Prisma.XOR<Prisma.TafUpdateWithoutClassInput, Prisma.TafUncheckedUpdateWithoutClassInput>
}

export type TafUpdateManyWithWhereWithoutClassInput = {
  where: Prisma.TafScalarWhereInput
  data: Prisma.XOR<Prisma.TafUpdateManyMutationInput, Prisma.TafUncheckedUpdateManyWithoutClassInput>
}

export type TafScalarWhereInput = {
  AND?: Prisma.TafScalarWhereInput | Prisma.TafScalarWhereInput[]
  OR?: Prisma.TafScalarWhereInput[]
  NOT?: Prisma.TafScalarWhereInput | Prisma.TafScalarWhereInput[]
  id?: Prisma.IntFilter<"Taf"> | number
  subjectId?: Prisma.IntNullableFilter<"Taf"> | number | null
  classId?: Prisma.IntNullableFilter<"Taf"> | number | null
  type?: Prisma.StringNullableFilter<"Taf"> | string | null
  dateTaf?: Prisma.DateTimeNullableFilter<"Taf"> | Date | string | null
  description?: Prisma.StringNullableFilter<"Taf"> | string | null
}

export type TafCreateWithoutSubjectInput = {
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
  class?: Prisma.ClassCreateNestedOneWithoutTafsInput
  files?: Prisma.fileCreateNestedManyWithoutTafInput
}

export type TafUncheckedCreateWithoutSubjectInput = {
  id?: number
  classId?: number | null
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
  files?: Prisma.fileUncheckedCreateNestedManyWithoutTafInput
}

export type TafCreateOrConnectWithoutSubjectInput = {
  where: Prisma.TafWhereUniqueInput
  create: Prisma.XOR<Prisma.TafCreateWithoutSubjectInput, Prisma.TafUncheckedCreateWithoutSubjectInput>
}

export type TafCreateManySubjectInputEnvelope = {
  data: Prisma.TafCreateManySubjectInput | Prisma.TafCreateManySubjectInput[]
  skipDuplicates?: boolean
}

export type TafUpsertWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.TafWhereUniqueInput
  update: Prisma.XOR<Prisma.TafUpdateWithoutSubjectInput, Prisma.TafUncheckedUpdateWithoutSubjectInput>
  create: Prisma.XOR<Prisma.TafCreateWithoutSubjectInput, Prisma.TafUncheckedCreateWithoutSubjectInput>
}

export type TafUpdateWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.TafWhereUniqueInput
  data: Prisma.XOR<Prisma.TafUpdateWithoutSubjectInput, Prisma.TafUncheckedUpdateWithoutSubjectInput>
}

export type TafUpdateManyWithWhereWithoutSubjectInput = {
  where: Prisma.TafScalarWhereInput
  data: Prisma.XOR<Prisma.TafUpdateManyMutationInput, Prisma.TafUncheckedUpdateManyWithoutSubjectInput>
}

export type TafCreateWithoutFilesInput = {
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
  class?: Prisma.ClassCreateNestedOneWithoutTafsInput
  subject?: Prisma.SubjectCreateNestedOneWithoutTafsInput
}

export type TafUncheckedCreateWithoutFilesInput = {
  id?: number
  subjectId?: number | null
  classId?: number | null
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
}

export type TafCreateOrConnectWithoutFilesInput = {
  where: Prisma.TafWhereUniqueInput
  create: Prisma.XOR<Prisma.TafCreateWithoutFilesInput, Prisma.TafUncheckedCreateWithoutFilesInput>
}

export type TafUpsertWithoutFilesInput = {
  update: Prisma.XOR<Prisma.TafUpdateWithoutFilesInput, Prisma.TafUncheckedUpdateWithoutFilesInput>
  create: Prisma.XOR<Prisma.TafCreateWithoutFilesInput, Prisma.TafUncheckedCreateWithoutFilesInput>
  where?: Prisma.TafWhereInput
}

export type TafUpdateToOneWithWhereWithoutFilesInput = {
  where?: Prisma.TafWhereInput
  data: Prisma.XOR<Prisma.TafUpdateWithoutFilesInput, Prisma.TafUncheckedUpdateWithoutFilesInput>
}

export type TafUpdateWithoutFilesInput = {
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.ClassUpdateOneWithoutTafsNestedInput
  subject?: Prisma.SubjectUpdateOneWithoutTafsNestedInput
}

export type TafUncheckedUpdateWithoutFilesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  subjectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TafCreateManyClassInput = {
  id?: number
  subjectId?: number | null
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
}

export type TafUpdateWithoutClassInput = {
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subject?: Prisma.SubjectUpdateOneWithoutTafsNestedInput
  files?: Prisma.fileUpdateManyWithoutTafNestedInput
}

export type TafUncheckedUpdateWithoutClassInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  subjectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.fileUncheckedUpdateManyWithoutTafNestedInput
}

export type TafUncheckedUpdateManyWithoutClassInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  subjectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TafCreateManySubjectInput = {
  id?: number
  classId?: number | null
  type?: string | null
  dateTaf?: Date | string | null
  description?: string | null
}

export type TafUpdateWithoutSubjectInput = {
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  class?: Prisma.ClassUpdateOneWithoutTafsNestedInput
  files?: Prisma.fileUpdateManyWithoutTafNestedInput
}

export type TafUncheckedUpdateWithoutSubjectInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  files?: Prisma.fileUncheckedUpdateManyWithoutTafNestedInput
}

export type TafUncheckedUpdateManyWithoutSubjectInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  classId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateTaf?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type TafCountOutputType
 */

export type TafCountOutputType = {
  files: number
}

export type TafCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  files?: boolean | TafCountOutputTypeCountFilesArgs
}

/**
 * TafCountOutputType without action
 */
export type TafCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TafCountOutputType
   */
  select?: Prisma.TafCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TafCountOutputType without action
 */
export type TafCountOutputTypeCountFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.fileWhereInput
}


export type TafSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subjectId?: boolean
  classId?: boolean
  type?: boolean
  dateTaf?: boolean
  description?: boolean
  class?: boolean | Prisma.Taf$classArgs<ExtArgs>
  subject?: boolean | Prisma.Taf$subjectArgs<ExtArgs>
  files?: boolean | Prisma.Taf$filesArgs<ExtArgs>
  _count?: boolean | Prisma.TafCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["taf"]>

export type TafSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subjectId?: boolean
  classId?: boolean
  type?: boolean
  dateTaf?: boolean
  description?: boolean
  class?: boolean | Prisma.Taf$classArgs<ExtArgs>
  subject?: boolean | Prisma.Taf$subjectArgs<ExtArgs>
}, ExtArgs["result"]["taf"]>

export type TafSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  subjectId?: boolean
  classId?: boolean
  type?: boolean
  dateTaf?: boolean
  description?: boolean
  class?: boolean | Prisma.Taf$classArgs<ExtArgs>
  subject?: boolean | Prisma.Taf$subjectArgs<ExtArgs>
}, ExtArgs["result"]["taf"]>

export type TafSelectScalar = {
  id?: boolean
  subjectId?: boolean
  classId?: boolean
  type?: boolean
  dateTaf?: boolean
  description?: boolean
}

export type TafOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "subjectId" | "classId" | "type" | "dateTaf" | "description", ExtArgs["result"]["taf"]>
export type TafInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.Taf$classArgs<ExtArgs>
  subject?: boolean | Prisma.Taf$subjectArgs<ExtArgs>
  files?: boolean | Prisma.Taf$filesArgs<ExtArgs>
  _count?: boolean | Prisma.TafCountOutputTypeDefaultArgs<ExtArgs>
}
export type TafIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.Taf$classArgs<ExtArgs>
  subject?: boolean | Prisma.Taf$subjectArgs<ExtArgs>
}
export type TafIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  class?: boolean | Prisma.Taf$classArgs<ExtArgs>
  subject?: boolean | Prisma.Taf$subjectArgs<ExtArgs>
}

export type $TafPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Taf"
  objects: {
    class: Prisma.$ClassPayload<ExtArgs> | null
    subject: Prisma.$SubjectPayload<ExtArgs> | null
    files: Prisma.$filePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    subjectId: number | null
    classId: number | null
    type: string | null
    dateTaf: Date | null
    description: string | null
  }, ExtArgs["result"]["taf"]>
  composites: {}
}

export type TafGetPayload<S extends boolean | null | undefined | TafDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TafPayload, S>

export type TafCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TafFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TafCountAggregateInputType | true
  }

export interface TafDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Taf'], meta: { name: 'Taf' } }
  /**
   * Find zero or one Taf that matches the filter.
   * @param {TafFindUniqueArgs} args - Arguments to find a Taf
   * @example
   * // Get one Taf
   * const taf = await prisma.taf.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TafFindUniqueArgs>(args: Prisma.SelectSubset<T, TafFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TafClient<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Taf that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TafFindUniqueOrThrowArgs} args - Arguments to find a Taf
   * @example
   * // Get one Taf
   * const taf = await prisma.taf.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TafFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TafFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TafClient<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Taf that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TafFindFirstArgs} args - Arguments to find a Taf
   * @example
   * // Get one Taf
   * const taf = await prisma.taf.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TafFindFirstArgs>(args?: Prisma.SelectSubset<T, TafFindFirstArgs<ExtArgs>>): Prisma.Prisma__TafClient<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Taf that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TafFindFirstOrThrowArgs} args - Arguments to find a Taf
   * @example
   * // Get one Taf
   * const taf = await prisma.taf.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TafFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TafFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TafClient<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tafs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TafFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tafs
   * const tafs = await prisma.taf.findMany()
   * 
   * // Get first 10 Tafs
   * const tafs = await prisma.taf.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tafWithIdOnly = await prisma.taf.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TafFindManyArgs>(args?: Prisma.SelectSubset<T, TafFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Taf.
   * @param {TafCreateArgs} args - Arguments to create a Taf.
   * @example
   * // Create one Taf
   * const Taf = await prisma.taf.create({
   *   data: {
   *     // ... data to create a Taf
   *   }
   * })
   * 
   */
  create<T extends TafCreateArgs>(args: Prisma.SelectSubset<T, TafCreateArgs<ExtArgs>>): Prisma.Prisma__TafClient<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tafs.
   * @param {TafCreateManyArgs} args - Arguments to create many Tafs.
   * @example
   * // Create many Tafs
   * const taf = await prisma.taf.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TafCreateManyArgs>(args?: Prisma.SelectSubset<T, TafCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tafs and returns the data saved in the database.
   * @param {TafCreateManyAndReturnArgs} args - Arguments to create many Tafs.
   * @example
   * // Create many Tafs
   * const taf = await prisma.taf.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tafs and only return the `id`
   * const tafWithIdOnly = await prisma.taf.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TafCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TafCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Taf.
   * @param {TafDeleteArgs} args - Arguments to delete one Taf.
   * @example
   * // Delete one Taf
   * const Taf = await prisma.taf.delete({
   *   where: {
   *     // ... filter to delete one Taf
   *   }
   * })
   * 
   */
  delete<T extends TafDeleteArgs>(args: Prisma.SelectSubset<T, TafDeleteArgs<ExtArgs>>): Prisma.Prisma__TafClient<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Taf.
   * @param {TafUpdateArgs} args - Arguments to update one Taf.
   * @example
   * // Update one Taf
   * const taf = await prisma.taf.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TafUpdateArgs>(args: Prisma.SelectSubset<T, TafUpdateArgs<ExtArgs>>): Prisma.Prisma__TafClient<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tafs.
   * @param {TafDeleteManyArgs} args - Arguments to filter Tafs to delete.
   * @example
   * // Delete a few Tafs
   * const { count } = await prisma.taf.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TafDeleteManyArgs>(args?: Prisma.SelectSubset<T, TafDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tafs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TafUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tafs
   * const taf = await prisma.taf.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TafUpdateManyArgs>(args: Prisma.SelectSubset<T, TafUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tafs and returns the data updated in the database.
   * @param {TafUpdateManyAndReturnArgs} args - Arguments to update many Tafs.
   * @example
   * // Update many Tafs
   * const taf = await prisma.taf.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tafs and only return the `id`
   * const tafWithIdOnly = await prisma.taf.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TafUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TafUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Taf.
   * @param {TafUpsertArgs} args - Arguments to update or create a Taf.
   * @example
   * // Update or create a Taf
   * const taf = await prisma.taf.upsert({
   *   create: {
   *     // ... data to create a Taf
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Taf we want to update
   *   }
   * })
   */
  upsert<T extends TafUpsertArgs>(args: Prisma.SelectSubset<T, TafUpsertArgs<ExtArgs>>): Prisma.Prisma__TafClient<runtime.Types.Result.GetResult<Prisma.$TafPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tafs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TafCountArgs} args - Arguments to filter Tafs to count.
   * @example
   * // Count the number of Tafs
   * const count = await prisma.taf.count({
   *   where: {
   *     // ... the filter for the Tafs we want to count
   *   }
   * })
  **/
  count<T extends TafCountArgs>(
    args?: Prisma.Subset<T, TafCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TafCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Taf.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TafAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TafAggregateArgs>(args: Prisma.Subset<T, TafAggregateArgs>): Prisma.PrismaPromise<GetTafAggregateType<T>>

  /**
   * Group by Taf.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TafGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TafGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TafGroupByArgs['orderBy'] }
      : { orderBy?: TafGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TafGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTafGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Taf model
 */
readonly fields: TafFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Taf.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TafClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  class<T extends Prisma.Taf$classArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Taf$classArgs<ExtArgs>>): Prisma.Prisma__ClassClient<runtime.Types.Result.GetResult<Prisma.$ClassPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  subject<T extends Prisma.Taf$subjectArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Taf$subjectArgs<ExtArgs>>): Prisma.Prisma__SubjectClient<runtime.Types.Result.GetResult<Prisma.$SubjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  files<T extends Prisma.Taf$filesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Taf$filesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$filePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Taf model
 */
export interface TafFieldRefs {
  readonly id: Prisma.FieldRef<"Taf", 'Int'>
  readonly subjectId: Prisma.FieldRef<"Taf", 'Int'>
  readonly classId: Prisma.FieldRef<"Taf", 'Int'>
  readonly type: Prisma.FieldRef<"Taf", 'String'>
  readonly dateTaf: Prisma.FieldRef<"Taf", 'DateTime'>
  readonly description: Prisma.FieldRef<"Taf", 'String'>
}
    

// Custom InputTypes
/**
 * Taf findUnique
 */
export type TafFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafInclude<ExtArgs> | null
  /**
   * Filter, which Taf to fetch.
   */
  where: Prisma.TafWhereUniqueInput
}

/**
 * Taf findUniqueOrThrow
 */
export type TafFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafInclude<ExtArgs> | null
  /**
   * Filter, which Taf to fetch.
   */
  where: Prisma.TafWhereUniqueInput
}

/**
 * Taf findFirst
 */
export type TafFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafInclude<ExtArgs> | null
  /**
   * Filter, which Taf to fetch.
   */
  where?: Prisma.TafWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tafs to fetch.
   */
  orderBy?: Prisma.TafOrderByWithRelationInput | Prisma.TafOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tafs.
   */
  cursor?: Prisma.TafWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tafs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tafs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tafs.
   */
  distinct?: Prisma.TafScalarFieldEnum | Prisma.TafScalarFieldEnum[]
}

/**
 * Taf findFirstOrThrow
 */
export type TafFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafInclude<ExtArgs> | null
  /**
   * Filter, which Taf to fetch.
   */
  where?: Prisma.TafWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tafs to fetch.
   */
  orderBy?: Prisma.TafOrderByWithRelationInput | Prisma.TafOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tafs.
   */
  cursor?: Prisma.TafWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tafs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tafs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tafs.
   */
  distinct?: Prisma.TafScalarFieldEnum | Prisma.TafScalarFieldEnum[]
}

/**
 * Taf findMany
 */
export type TafFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafInclude<ExtArgs> | null
  /**
   * Filter, which Tafs to fetch.
   */
  where?: Prisma.TafWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tafs to fetch.
   */
  orderBy?: Prisma.TafOrderByWithRelationInput | Prisma.TafOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tafs.
   */
  cursor?: Prisma.TafWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tafs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tafs.
   */
  skip?: number
  distinct?: Prisma.TafScalarFieldEnum | Prisma.TafScalarFieldEnum[]
}

/**
 * Taf create
 */
export type TafCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafInclude<ExtArgs> | null
  /**
   * The data needed to create a Taf.
   */
  data?: Prisma.XOR<Prisma.TafCreateInput, Prisma.TafUncheckedCreateInput>
}

/**
 * Taf createMany
 */
export type TafCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tafs.
   */
  data: Prisma.TafCreateManyInput | Prisma.TafCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Taf createManyAndReturn
 */
export type TafCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * The data used to create many Tafs.
   */
  data: Prisma.TafCreateManyInput | Prisma.TafCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Taf update
 */
export type TafUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafInclude<ExtArgs> | null
  /**
   * The data needed to update a Taf.
   */
  data: Prisma.XOR<Prisma.TafUpdateInput, Prisma.TafUncheckedUpdateInput>
  /**
   * Choose, which Taf to update.
   */
  where: Prisma.TafWhereUniqueInput
}

/**
 * Taf updateMany
 */
export type TafUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tafs.
   */
  data: Prisma.XOR<Prisma.TafUpdateManyMutationInput, Prisma.TafUncheckedUpdateManyInput>
  /**
   * Filter which Tafs to update
   */
  where?: Prisma.TafWhereInput
  /**
   * Limit how many Tafs to update.
   */
  limit?: number
}

/**
 * Taf updateManyAndReturn
 */
export type TafUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * The data used to update Tafs.
   */
  data: Prisma.XOR<Prisma.TafUpdateManyMutationInput, Prisma.TafUncheckedUpdateManyInput>
  /**
   * Filter which Tafs to update
   */
  where?: Prisma.TafWhereInput
  /**
   * Limit how many Tafs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Taf upsert
 */
export type TafUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafInclude<ExtArgs> | null
  /**
   * The filter to search for the Taf to update in case it exists.
   */
  where: Prisma.TafWhereUniqueInput
  /**
   * In case the Taf found by the `where` argument doesn't exist, create a new Taf with this data.
   */
  create: Prisma.XOR<Prisma.TafCreateInput, Prisma.TafUncheckedCreateInput>
  /**
   * In case the Taf was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TafUpdateInput, Prisma.TafUncheckedUpdateInput>
}

/**
 * Taf delete
 */
export type TafDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafInclude<ExtArgs> | null
  /**
   * Filter which Taf to delete.
   */
  where: Prisma.TafWhereUniqueInput
}

/**
 * Taf deleteMany
 */
export type TafDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tafs to delete
   */
  where?: Prisma.TafWhereInput
  /**
   * Limit how many Tafs to delete.
   */
  limit?: number
}

/**
 * Taf.class
 */
export type Taf$classArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Class
   */
  select?: Prisma.ClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Class
   */
  omit?: Prisma.ClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClassInclude<ExtArgs> | null
  where?: Prisma.ClassWhereInput
}

/**
 * Taf.subject
 */
export type Taf$subjectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subject
   */
  select?: Prisma.SubjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subject
   */
  omit?: Prisma.SubjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectInclude<ExtArgs> | null
  where?: Prisma.SubjectWhereInput
}

/**
 * Taf.files
 */
export type Taf$filesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the file
   */
  select?: Prisma.fileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the file
   */
  omit?: Prisma.fileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.fileInclude<ExtArgs> | null
  where?: Prisma.fileWhereInput
  orderBy?: Prisma.fileOrderByWithRelationInput | Prisma.fileOrderByWithRelationInput[]
  cursor?: Prisma.fileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FileScalarFieldEnum | Prisma.FileScalarFieldEnum[]
}

/**
 * Taf without action
 */
export type TafDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Taf
   */
  select?: Prisma.TafSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Taf
   */
  omit?: Prisma.TafOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TafInclude<ExtArgs> | null
}
