
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Student
 * 
 */
export type Student = Prisma.StudentModel
/**
 * Model Parent
 * 
 */
export type Parent = Prisma.ParentModel
/**
 * Model StudentDocument
 * 
 */
export type StudentDocument = Prisma.StudentDocumentModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model PaymentLine
 * 
 */
export type PaymentLine = Prisma.PaymentLineModel
/**
 * Model Teacher
 * 
 */
export type Teacher = Prisma.TeacherModel
/**
 * Model Class
 * 
 */
export type Class = Prisma.ClassModel
/**
 * Model Room
 * 
 */
export type Room = Prisma.RoomModel
/**
 * Model Schedule
 * 
 */
export type Schedule = Prisma.ScheduleModel
/**
 * Model Subject
 * 
 */
export type Subject = Prisma.SubjectModel
/**
 * Model Taf
 * 
 */
export type Taf = Prisma.TafModel
/**
 * Model Event
 * 
 */
export type Event = Prisma.EventModel
/**
 * Model Activity
 * 
 */
export type Activity = Prisma.ActivityModel
/**
 * Model Absence
 * 
 */
export type Absence = Prisma.AbsenceModel
/**
 * Model TeacherAbsence
 * 
 */
export type TeacherAbsence = Prisma.TeacherAbsenceModel
/**
 * Model AdminAlert
 * 
 */
export type AdminAlert = Prisma.AdminAlertModel
/**
 * Model Planing
 * 
 */
export type Planing = Prisma.PlaningModel
/**
 * Model SessionEvaluation
 * 
 */
export type SessionEvaluation = Prisma.SessionEvaluationModel
/**
 * Model Ressouce
 * 
 */
export type Ressouce = Prisma.RessouceModel
/**
 * Model file
 * 
 */
export type file = Prisma.fileModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Note
 * 
 */
export type Note = Prisma.NoteModel
/**
 * Model NoteDevoir
 * 
 */
export type NoteDevoir = Prisma.NoteDevoirModel
/**
 * Model Chat
 * 
 */
export type Chat = Prisma.ChatModel
/**
 * Model GlobalSetting
 * 
 */
export type GlobalSetting = Prisma.GlobalSettingModel
