
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Student'
export type * from './models/Parent'
export type * from './models/StudentDocument'
export type * from './models/Payment'
export type * from './models/PaymentLine'
export type * from './models/Teacher'
export type * from './models/Class'
export type * from './models/Room'
export type * from './models/Schedule'
export type * from './models/Subject'
export type * from './models/Taf'
export type * from './models/Event'
export type * from './models/Activity'
export type * from './models/Absence'
export type * from './models/TeacherAbsence'
export type * from './models/AdminAlert'
export type * from './models/Planing'
export type * from './models/SessionEvaluation'
export type * from './models/Ressouce'
export type * from './models/file'
export type * from './models/Notification'
export type * from './models/Note'
export type * from './models/NoteDevoir'
export type * from './models/Chat'
export type * from './models/GlobalSetting'
export type * from './commonInputTypes'